### ISSUE TITLE
Network error after login

### ISSUE THREAD

**Issue by dw72** [neffo/bing-wallpaper-gnome-extension#1]
The extension should wait for network connectivity before downloading the wallpaper. Now throws a network error and does not re-download.

**Comment by neffo** [comment]
Ah, good point. Error handling is pretty minimal. It should retry 24 hours later, but that's pretty terrible. I'll fix it.

**Comment by 4thguy** [comment]
So that's the source of the error! Glad to know that it's this and not something more serious

**Comment by neffo** [comment]
A new version is pending review on GNOME extensions which should help with this issue. I don't know how best to detect an active network connection, but the error shouldn't cause GNOME to complain. It will now also retry in just one hour (after an error), instead of waiting a whole day.

**Comment by 4thguy** [comment]
Just to be clear, it just shows an error icon next to the extension for me

**Comment by dw72** [comment]
I don't know if this work in gnome but try this:

```js
if(navigator.onLine) {
    console.log("online");
} else {
    console.log("offline");
}
```

**Comment by neffo** [comment]
@4thguy I am seeing that in the tweak tool also, but I'm not seeing any errors in the journal. There were a few bugs I fixed that might have been causing silent errors, but I couldn't positively confirm that. The updates are still pending on gnome extensions however.

(I didn't expect it to get as much attention as it did, so I published it a little bit unfinished.)

**Comment by neffo** [comment]
Closing this out, as it seems to be fixed now.
