### ISSUE TITLE
No longer Compatible with GNOME 40.1.0

### ISSUE THREAD

**Issue by SilverAeroNZ** [neffo/bing-wallpaper-gnome-extension#104]
Could it be updated please?

**Comment by neffo** [comment]
Do you mean GNOME 41?

Which OS and version?

**Comment by SilverAeroNZ** [comment]
It's Fedora 34 Stable it's still GNOME 40 it's an minor update to 40.1 not 41. The GNOME Extensions website states that it is incompatible.

**Comment by neffo** [comment]
Ahh yes, this may be a bug with the extension or the tool. Point releases should not break compatibility nor should the extension need to be updated. I'll update the extension metadata to include point releases even if it's technically correct. Unless a fix is already on the way from GNOME... Sorry for inconvenience.

**Comment by SilverAeroNZ** [comment]
Thanks for the info!

**Comment by neffo** [comment]
Ahhh, my bad this is my fault! [At least according to this](https://gitlab.gnome.org/Infrastructure/extensions-web/-/issues/131)

**Comment by neffo** [comment]
Should be fixed in version 32 now approved on [extensions.gnome.org](https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/). Thanks for the report.
