### ISSUE TITLE
Refreshing causes Gnome Shell to fatal crash

### ISSUE THREAD

**Issue by mkaput** [neffo/bing-wallpaper-gnome-extension#11]
Refreshing wallpaper causes Gnome Shell to crash on my machine since the update, making extension unusable (shell crashes every few seconds).

I can't find something related in `journalctl`

Version: v9 from Gnome extension repository
Fedora 26 Workstation

**Comment by ganloo** [comment]
I got the same issue with today's update, I am running Arch Linux current,  extension v9 from GNOME official extension website.
Gnome shell crashes under wayland and xorg server, only the shell will automatically restart under xorg and will reload to gdm if under wayland.

**Comment by neffo** [comment]
Ahh, I was testing some Unity Greeter/LightDM code. That you are both on non-Ubuntu distros suggests it could be that.

I've pushed some commits that remove it, if you want to test that with the git version.

**Comment by neffo** [comment]
I was able to confirm this bug by removing LightDM, and the dconf keys. (The later seems to be the specific cause of the bug.)

I'll upload a version to extensions.gnome.org that corrects this (but this will take a day or so to get approved), in the mean time you can download and install the v10 zip file from here.

Or, you can comment out the line below in extensions.js (line 167):

> `doSetBackgroundLightDM(this.filename, 'com.canonical.unity-greeter');`

**Comment by mkaput** [comment]
Thanks! <3

**Comment by mkaput** [comment]
Nope, it still crashes on my machine with this comment

**Comment by neffo** [comment]
Hmm, two crash bugs in one release? 🔥

Hmm, ok, the other change with this release was adding 'file://' to the 'picture-uri' key. This should be the correct behaviour though...

**Comment by mkaput** [comment]
This line from logs precedes core dump:

```
gnome-shell[3308]: Settings schema 'org.gnome.desktop.background' does not contain a key named 'draw-background'
```

**Comment by mkaput** [comment]
https://github.com/neffo/bing-wallpaper-gnome-extension/commit/817884a85f521905ab6106b6b28934f27c88002a#diff-06f1274e40de25abda72d812b1cce86aR91

This line caused regression

**Comment by neffo** [comment]
Ah, that's a deprecated key, and it's not in the Fedora 26 schemas.

**Comment by raymondhuo** [comment]
![default](https://user-images.githubusercontent.com/23137940/29440140-07245ff4-83f5-11e7-9e3b-662dc8339e5e.png)
i'm using ubuntu,but still crash.this is my log

**Comment by neffo** [comment]
Hi, could you please tell me which extension version you are running?

Did you install from extensions.gnome.org?

**Comment by neffo** [comment]
Version 11 is still pending review (this fixes this bug), but has been stuck in the queue for about a week now. I've reverted the active version to 7 as this is likely the most compatible version. This will bring back other bugs though...

**Comment by raymondhuo** [comment]
first install in extensions.gnome.org,because of crash i'am reinstallde in ubuntu software store. 
have a good time.

**Comment by ganloo** [comment]
I use 'git clone' to install r11, which works like a charm.

**Comment by neffo** [comment]
You can also use this [zip file](https://neffo.github.io/BingWallpaper@ineffable-gmail.com.zip) (and install via Gnome Tweak Tool).

**Comment by neffo** [comment]
@mkaput @ganloo @raymondhuo can you confirm this crash bug is fixed for you with the latest version (v12)?

**Comment by mkaput** [comment]
yep, everything works now!

**Comment by raymondhuo** [comment]
@neffo  the bug has been fixed . thank you .
