### ISSUE TITLE
Try to choose market following locale

### ISSUE THREAD

**Issue by pacho2** [neffo/bing-wallpaper-gnome-extension#112]
Hello,

One thing I miss is that bing wallpaper is always used from en-US, I can change it manually, but it would be nice if there was an "auto" mode trying to use the market according to user's locale or location and fallback to en-US if not possible.

Thanks a lot

**Comment by neffo** [comment]
Yeah, this seems sensible and shouldn't be a problem to do.

**Comment by neffo** [comment]
This functionality should be live now. This works by selecting 'auto' from the locale drop down, which is now the default (on fresh installs at least).

**Comment by pacho2** [comment]
Works perfectly, thanks a lot!

**Comment by neffo** [comment]
Thanks for letting me know.
