### ISSUE TITLE
Store copyright/image info to file or image metadata

### ISSUE THREAD

**Issue by bbogner** [neffo/bing-wallpaper-gnome-extension#119]
Is it possible to store the image details from copyright to a text file? 
Similiar as in UtkarshGpta bing-desktop-wallpaper-changer?
Or could it be part of the images metadata?
Sometimes it's nice to be able to find this info again, even it's not available through bing anymore.

**Comment by neffo** [comment]
The metadata is stored locally, but within GNOME settings. We basically store and aggregate all the raw JSON data from Bing, the data is kept so long as the images remain on disk although they are stored separately. (Image metadata is only deleted when the images are deleted.)

If you flick back through the older images via the menu or the preferences drop down it will display this information in the menu.

The example below is from the Bing wallpaper for 23 May 2021:

![image](https://user-images.githubusercontent.com/5569112/125183749-58d2a300-e25c-11eb-8433-563ca8c47a71.png)
