### ISSUE TITLE
This wallpaper extension won't change my dsesktopn and lock screen wallaper

### ISSUE THREAD

**Issue by fwzmhmd** [neffo/bing-wallpaper-gnome-extension#12]
This extension won't even change my wallpaper after it has refresh after a day or two.

OS: Ubuntu 16.04

**Comment by neffo** [comment]
Does manually setting a download folder fix the issue?

**Comment by yura-pakhuchiy** [comment]
Same problem here.

@neffo Yes, it seems does fix the issue.

**Comment by neffo** [comment]
@fwzmhmd @yura-pakhuchiy is this bug fixed for you with the latest release (v12)?

**Comment by yura-pakhuchiy** [comment]
@neffo not sure how to test, it works find since I selected download directory manually
