### ISSUE TITLE
Feature request: shuffle & refresh more often

### ISSUE THREAD

**Issue by carlthome** [neffo/bing-wallpaper-gnome-extension#121]
This extension is wonderful and I really dig the polish it's been getting recently!

With the "Set a random wallpaper" button now available, I wonder if it would also be possible to click that automatically every couple of minutes?

Assuming the user keeps around downloaded wallpapers, a random choice on a time-based trigger would make this extension perfect for my setup. I'm trying to prevent OLED burn-in without resorting to a solid black background.

**Comment by neffo** [comment]
Hi Carl, thanks for your comment and thanks for the suggestion. This is actually implemented but not exposed by the preferences at the moment, but definitely something that can be added easily.

Here is how to change it manually:
`GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas dconf-editor /org/gnome/shell/extensions/bingwallpaper/random-interval
`

Then you can set the number of seconds between each change.

![image](https://user-images.githubusercontent.com/5569112/128945687-afe7b96d-e336-4e63-860d-6a36dbddb5f2.png)

**Comment by neffo** [comment]
Have initial adjustable version in #117

**Comment by neffo** [comment]
Hopefully this did the trick?

![image](https://user-images.githubusercontent.com/5569112/135260387-8bd8bc51-83a2-44a1-8325-808844341961.png)

**Comment by shea-sollars** [comment]
How can I refresh the image from command line, so that I can add it as a startup command?
