### ISSUE TITLE
Bing Wallpaper for gdm login screen

### ISSUE THREAD

**Issue by mansoormemon** [neffo/bing-wallpaper-gnome-extension#131]
Can you make bing wallpaper work with gdm login screen to update my wallpaper daily?

**Comment by neffo** [comment]
This isn't possible in the same way, it requires updating global configuration with super user actions. Not something you'd want a GNOME extension playing with, I don't think.

There are some tools that let you do that, such as [this one](https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background). It might be possible to configure GDM to accept a wallpaper slideshow (an XML file with a list of wallpapers filenames in it), but not sure.

**Comment by mansoormemon** [comment]
Thanks!
