### ISSUE TITLE
Add a link to Bing?

### ISSUE THREAD

**Issue by alexislefebvre** [neffo/bing-wallpaper-gnome-extension#132]
Hello,
is it possible to add a link to Bing in the extension menu? Ideally it would redirect to the page of the current day, for example: https://www.bing.com/search?q=chocolate+hills+bohol&form=hpcapt&filters=HpDate:%2220211123_2300%22

It could also lead to Bing's homepage https://www.bing.com/ because it contains the link that present the photo of the day.

**Comment by neffo** [comment]
Hi Alexis,

It appears that I have introduced a bug in the latest version. The image description should link to Bing's description of the image. Should be an easy fix to push out.

Thanks for the report and support.

**Comment by alexislefebvre** [comment]
I updated the extension and it works. Thanks!
