### ISSUE TITLE
[BUG] Hide/Unhide indicator toggle only works after log out/reboot

### ISSUE THREAD

**Issue by forteller** [neffo/bing-wallpaper-gnome-extension#135]
Hi. Thanks for a really nice extension!

**Describe the bug**
Just wanted to note that changing the state of the "Hide the indicator" setting only take effect after logging out and back in again. Not sure if this is a bug or intended, but I know other extensions are able to turn the indicator on and off instantly, and if it is intended it would be nice if it said "(needs reboot)" or something, so it's not as confusing.

Thanks! :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Extension Version: It doesn't say which version on the About page for the extension settings, but it says it's a hotfix for v 35, so I'm guessing it's 36
 - GNOME Version: 40.4

**Additional context**
Using Gnome-session

**Comment by neffo** [comment]
Thanks for report, looks like this was a bug introduced in recent changes to more modern code standards.
