### ISSUE TITLE
[Feature request] Migrate images to other computer (i.e. export/import image library)

### ISSUE THREAD

**Issue by detectivekid** [neffo/bing-wallpaper-gnome-extension#136]
Hi,

I recently had to change distros, but noticed I don’t have access to all the old bing photos I’ve collected over time.

I can’t find an import button. I’ve set the folder to the same one I was using previously, but it doesn’t seem to import the images into the program. I tried copying the data from .local/share/gnome-shell/extensions, but it appears to have no effect. At the moment I’m running 2 daemons, one to shuffle my backgrounds and the bing one to grab new photos. Not the best situation, since they both fight for control.

Slap me on the head if I'm being stupid, but I was wondering if there was a method to import new/old photos, or if there were plans to?

By the looks of things you mention here (https://github.com/neffo/bing-wallpaper-gnome-extension/issues/119) that some of the data is stored in the gnome settings, but I’m not sure if it’s relevant is this context.

Cheers.

**Comment by detectivekid** [comment]
OS: Manjaro Linux x86_64 
Kernel: 5.15.5-AMD 
DE: GNOME 41.1
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT / 6800M 

My info, if relevant at all.

**Comment by neffo** [comment]
Currently there isn't an import option (nor export). You could do this manually at the moment, though I haven't tested this yet.

On the original machine:
```
GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas dconf-editor /org/gnome/shell/extensions/bingwallpaper/
```
Then copy the bing-json key data, and save this to a text file:
![image](https://user-images.githubusercontent.com/5569112/144521068-14c8ff7c-7013-438b-ba8a-6d0f18594071.png)

Then on the new machine, open settings as above, and then overwrite the settings for bing-json with just the JSON component of that text file (including the outer square brackets, but not the inverted commas):

![image](https://user-images.githubusercontent.com/5569112/144521539-55aa31ce-7e6d-488c-a86c-c781e1c8383e.png)

I've trimmed the above to make it fit on one page, but obviously you will have a lot more JSON data.

If you've got the images save there and other settings are the same (such as Bing market) the extension should pick these up just fine. (But again, I haven't checked this.) If it does break the extension you may have to reset this field to default. Please let me know if this helps.

I could definitely implement a function to do this, so this is a great suggestion.

**Comment by detectivekid** [comment]
Hey, nice stuff!

Worked like a charm and gave me an opportunity to learn how dconf and gsettings function, which is always advantageous I suppose.

Could be a good idea to add this guide in the readme until an actual import feature is implemented? Up to you, I guess.

Cheers for the help.

**Comment by neffo** [comment]
I'll just implement the tools to do it in the extension.

**Comment by detectivekid** [comment]
Just as a note: I had already imported the image files to the library. I'm not sure if just importing the JSON data pulls the images.

**Comment by neffo** [comment]
The JSON is the primary record of images, the extension can't identify images that aren't referenced in the JSON image list and add them.

If you import JSON data for older images and the extension can't find those images in the wallpaper directory it will purge these 'zombie' images from the list of images. Images that are less than 8 days old can still be downloaded from Bing.

I think ideally, the JSON could be stored in the wallpaper directory, so migrating the library would just be a matter of copying the whole folder (images and all) and clicking 'Import'.

![image](https://user-images.githubusercontent.com/5569112/144730714-59dc91ba-e0ab-45d8-a0eb-6b32448c1589.png)
