### ISSUE TITLE
[BUG] Caption in the top-right menu is truncated

### ISSUE THREAD

**Issue by bdaase** [neffo/bing-wallpaper-gnome-extension#138]
**Describe the bug**

Since not so long ago, the caption in the top-right menu is truncated.

**Screenshots**

![image](https://user-images.githubusercontent.com/24682367/144705076-00744235-9c56-4014-8448-8db4d13c54a7.png)

**To Reproduce**
1. Click the icon in the top panel

**Desktop (please complete the following information):**
* Fedora 35
* Gnome 41.1
* Extension Version 36

**Additional context**

This started to happen quite recently, but I have no idea what has actually changed in between...

**Comment by neffo** [comment]
Strange, don't see it in English on GNOME 40.5.

![image](https://user-images.githubusercontent.com/5569112/144706089-71f2b398-f31f-4bb7-86b5-d9cf944d35e7.png)

What do you see if you hover over the image in the image gallery? I presume this is the German language/German Bing market?

I see this (in English):
![image](https://user-images.githubusercontent.com/5569112/144706193-e4da6169-1b8a-4cea-9a35-8b0dba9b9818.png)

**Comment by bdaase** [comment]
Yeah, it's German locale.


Everything looks fine in the image gallery

![image](https://user-images.githubusercontent.com/24682367/144706335-c40a2d62-9d88-436c-b100-d8400e21e5a3.png)

**Comment by bdaase** [comment]
It's also truncated in English btw

![image](https://user-images.githubusercontent.com/24682367/144706470-0560fb1c-46f5-42a2-a017-a83d38e57307.png)

**Comment by neffo** [comment]
Ahh, this must be a GNOME 41 thing.

I see this with the German locale:
![image](https://user-images.githubusercontent.com/5569112/144706291-1d625b7b-a312-451a-b35b-25f272ae3315.png)

And in GNOME 41 VM machine, I see this:
![image](https://user-images.githubusercontent.com/5569112/144706483-28235227-2c5d-4fdd-b2b2-41f8c6c4beb1.png)

**Comment by bdaase** [comment]
Glad that you can reproduce it :+1:

**Comment by neffo** [comment]
Yeah, thanks for reporting it. This seems like it could be a bug that was introduced in St.Label or some CSS. It's strange as the line looks like it has expanded vertically, but hasn't wrapped the text.

**Comment by neffo** [comment]
May have found a fix for it:
![image](https://user-images.githubusercontent.com/5569112/144741469-31173ce3-facf-4050-ba63-763479b945ae.png)

**Comment by bdaase** [comment]
Looks like the problem was fixed by a recent GNOME update?

![image](https://user-images.githubusercontent.com/24682367/145669587-a28820e4-72e4-436c-b87b-b56990882449.png)

I quickly grepped through my update history and the only change that might explain it, is the update from pango-1.49.3-2.fc35.x86_64 to pango-1.50.0-1.fc35.x86_64.

So maybe a fix in the extension isn't even required. Sorry for the noise...

**Comment by neffo** [comment]
No problem at all, this label wasn't sized correctly anyway, so should look better in this version when word-wrapped.
