### ISSUE TITLE
minor aesthetic issues in settings window

### ISSUE THREAD

**Issue by dasnoopy** [neffo/bing-wallpaper-gnome-extension#15]
Hi,  play a bit with this interesting extension i noticed some  few minor issue in settings window :

1) there is a lot of unused space at the  bottom...
2) comment label  for "bing locale" and "Screen resolution" are not aligned like e.g. Notifications
3) could be reduced in width  and aligned ,the input fields for options at point 2 (imo are too wide)
4) could be possibile reduce a bit  the top/bottom padding between options (it seems to much, imo)

Thanks in advance

**Comment by dasnoopy** [comment]
Maybe a screenshoot could help :) 
![screenshot from 2017-08-22 18-07-58](https://user-images.githubusercontent.com/296922/29576352-c97ae832-8767-11e7-8aee-aab0075c617f.png)

**Comment by neffo** [comment]
Ah yeah, all good points.

Also, I want to change those last two fields into "drop downs".

**Comment by neffo** [comment]
This a bit nicer on the eyes? 🎨
![screenshot from 2017-08-25 21-50-40](https://user-images.githubusercontent.com/5569112/29712979-d39d74ea-89df-11e7-813b-d08f3fe16310.png)

**Comment by dasnoopy** [comment]
...really much better.   :-)
