### ISSUE TITLE
[BUG] No settings if GNOME Soup 2.4 isn't available

### ISSUE THREAD

**Issue by ron-png** [neffo/bing-wallpaper-gnome-extension#150]
>NOTE:
>GNOME will sometimes report errors associated extensions if you manually update them via the extensions website. These errors can be resolved by restarting GNOME shell (logging out and then back in again). If it's still creating errors, then please go ahead create an issue.

**Describe the bug**
No settings

**Screenshots**
![Bildschirmfoto vom 2022-01-10 22-58-28](https://user-images.githubusercontent.com/41197190/148846123-a00146b1-1729-44a1-9a5e-5be010105d63.png)
![Bildschirmfoto vom 2022-01-10 22-58-56](https://user-images.githubusercontent.com/41197190/148846127-ed61627d-a429-480d-91d3-113bcc6796a1.png)

**To Reproduce**
1. Go to 'Extensions -> settings of Extension'

**Desktop (please complete the following information):**
 - OS: [EndeavourOS]
 - Extension Version: [e.g. 37]
 - GNOME Version: [e.g. 41.2]

**Comment by neffo** [comment]
Thanks for bug report, likely this is due to missing GNOME support for Soup 2.4. You may be able to install a 'gnome soup 2.4' package to restore this. Some distributions (e.g. GNOME) still package it with GNOME it appears.

**Comment by sidro** [comment]
pacman -Ss soup
extra/libsoup 2.74.2-2 [installed]
    HTTP client/server library for GNOME
extra/libsoup3 3.0.4-2 [installed]
    HTTP client/server library for GNOME

The settings of extension BingWallpaper@ineffable-gmail.com had an error:
```
TypeError: Soup.SessionAsync is not a constructor
```

Stack trace:
```
buildPrefsWidget@/home/sidro/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/prefs.js:94:19
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by neffo** [comment]
I trust this issue has been resolved with latest version?
