### ISSUE TITLE
[Feature request] Add a button to stop changing the backgound

### ISSUE THREAD

**Issue by eugene-ganshin** [neffo/bing-wallpaper-gnome-extension#152]
GIVEN a switch button to stop changing the background
WHEN the button is switched to "yes"
THEN application works as it should
WHEN the button is switched to "no"
THEN application does nothing

**Comment by neffo** [comment]
If I'm understanding this correctly, this is already an option here:

![image](https://user-images.githubusercontent.com/5569112/154471338-0eaa3fff-789e-4c9e-97c9-617cc004310f.png)

**Comment by zilexa** [comment]
What he means is a *Pause* button that is easily accessible. Just like Variety has. When you really like a wallpaper, just hit pause to enjoy it until you are ready for the next :) 

It's one of the reasons I still use Variety.

**Comment by neffo** [comment]
Right, understood. Easy enough to implement, it would essentially just be a toggle for this option in the menus.

(I've never used variety, I can't see screenshots anywhere.)

**Comment by neffo** [comment]
Some initial tests of pause button and shuffle toggle, seems to work ok. Buttons are a bit small though.

https://user-images.githubusercontent.com/5569112/161568216-6546b6a8-d587-4470-9b15-da812b740993.mp4

**Comment by zilexa** [comment]
This is great!
