### ISSUE TITLE
[BUG] Doesn't set the background image in GNOME 42

### ISSUE THREAD

**Issue by bdaase** [neffo/bing-wallpaper-gnome-extension#153]
That's just a quick heads up, that the background image doesn't seem to be set anymore in GNOME 42.

**Comment by neffo** [comment]
I believe this is fixed in version 38 #144 (unreleased at this time), I'm still trying to solve some other issues at the moment so I haven't pushed this out. I generally try to have a version out as soon as possible after a GNOME release.

**Comment by bdaase** [comment]
Awesome, and thanks a lot! I have just tested it on 42 and thought I let you know so that you have some time to react :)

**Comment by neffo** [comment]
Latest git appears to be working:
![image](https://user-images.githubusercontent.com/5569112/158406424-beae9fef-2a9e-4f91-a105-eb00d98f75be.png)

I'm also seeing the image disappearing on hover, might be fixable with CSS. Gallery is broken atm, but probably not a show stopper (I can just disable it).

**Comment by lsatenstein** [comment]
If the changes from one release to another are just the gnome version to gnome version number, is it possible, in the gui interface, add the 2 character field to allow the user to match the proper version to gnome.

**Comment by neffo** [comment]
Do you mean in the extension metadata.json? No, in this case there have been some changes with the gsettings keys used for the wallpaper in GNOME 42.
