### ISSUE TITLE
[BUG] Extension does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by leoheck** [neffo/bing-wallpaper-gnome-extension#154]
Hi Just installed the new (beta) Ubuntu 22.04 and it looks like the extension does not work there yet.
![image](https://user-images.githubusercontent.com/1277920/159057610-77cdde4e-1afa-4dc5-a275-2bab4f453e8b.png)

**Comment by neffo** [comment]
Yep this is known, WIP version 38 #144 is working but this isn't released yet.
