### ISSUE TITLE
Select from image gallery opens Nautilus, cannot set background image. 

### ISSUE THREAD

**Issue by Tj-Ward** [neffo/bing-wallpaper-gnome-extension#162]
In Gnome 42, the button "Select from image gallery" opens the regular file browser, not letting the user select am image.

I am experiencing this on OpenSUSE Tumbleweed.

**Comment by neffo** [comment]
GNOME 42 changed some things that broke the image gallery. I've not been able to work out what has changed to resolve it, opening Nautilus is a bit of a temporary work around to allow users to delete images at least.

**Comment by neffo** [comment]
![image](https://user-images.githubusercontent.com/5569112/161972096-c7a1130c-5096-4366-912c-e482b4ff38a7.png)
