### ISSUE TITLE
AUR package outdated 

### ISSUE THREAD

**Issue by zilexa** [neffo/bing-wallpaper-gnome-extension#164]
I use Manjaro Gnome.
One of the main benefits of this distribution is that it's software center pamac keeps everything up to date automatically, the OS, applications and even Gnome extensions that have been installed via Pamac (AUR repository).

I noticed this extension is also available and you are involved in the AUR package, but it's outdated:

https://aur.archlinux.org/packages/gnome-shell-extension-bing-wallpaper

Any reason why? I thought most of the extensions in AUR simply auto update when there is a new release on GitHub?

**Comment by neffo** [comment]
I don't maintain the arch package. I'd suggest you ask the maintainer at that link to review. This shouldn't really be needed as GNOME can manage the updates itself.

**Comment by zilexa** [comment]
I will definitely ask the maintainer. But what do you mean with Gnome managing the update itself?
As far as I know, Gnome has no extension update mechanism.. (sorry for going offtopic here)

**Comment by zilexa** [comment]
I did not know that!
I deliberately install via the package manager, to ensure updates come in. 
Now I understand I can indeed still install via package manager, and Gnome should automatically update it. 

I never understood why, to install very basic GUI stuff, a browser with a special extension was needed. That is why I install through the package manager, it makes more sense to me. 

I will now just install via package manager and check again after a day or so what version I am on. Thanks!

**Comment by neffo** [comment]
I'm not entirely sure how GNOME handles system installed extensions (like AUR packages). You can see what version you have in the about page of the extension settings (latest at the time of posting is 39).

**Comment by zilexa** [comment]
Thanks for that tip! I tried it and this should be the default Extension Manager (instead of the current "Extensions) !
Not sure if it will update my system extensions (thats how extensions installed via Pamac/AUR appear). But this is a really good one :)
