### ISSUE TITLE
[FEATURE REQUEST] Allow interval of days

### ISSUE THREAD

**Issue by zilexa** [neffo/bing-wallpaper-gnome-extension#165]
Currently the max interval is 86400 seconds (24 hours). Please consider allowing an interval of x days. There are days I barely (or not at all) see my wallpaper because my browser and other stuff is fullscreen the whole time. I would miss pretty wallpapers.
I usually enjoy a great wallpaper for a week, easily :)

**Comment by neffo** [comment]
![image](https://user-images.githubusercontent.com/5569112/165023824-40a47c9f-a562-4e77-bf94-cc0af14c5dba.png)

this should be live in version 40 (soon)
