### ISSUE TITLE
Stretched thumbnail in extensions menu

### ISSUE THREAD

**Issue by Etamuk** [neffo/bing-wallpaper-gnome-extension#167]
Hello,

I noticed that some pictures are streched in the extensions menu (see screenshot please). 
It's not a really big problem, just cosmetics.

It would be nice, all pictures would keep their proportion. 

![Bildschirmfoto von 2022-04-15 12-04-47-50P](https://user-images.githubusercontent.com/20098065/163558890-a31ded34-a6a7-4618-be4b-dd99b0fe87f9.png)
Best wishes

**Comment by neffo** [comment]
Not really sure how this is happening, did one of the descriptions or copyright's have a very long German word in it?

**Comment by Etamuk** [comment]
I don´t think so. 
This happens with many pictures. This is only one example. The Bing-Wallpaper from today is also affected. And it's description is very short. A line wrap would be possible at every word (maybe except "New Jersey").
![Bildschirmfoto von 2022-04-17 10-45-37 geaendert](https://user-images.githubusercontent.com/20098065/163707524-fedf3405-3ac0-427c-b923-2cb5b4d27aa3.png)


This picture has a very very short description and copyright info:

![Bildschirmfoto von 2022-04-17 10-51-47 geaendert](https://user-images.githubusercontent.com/20098065/163707658-9e07b442-a4b7-4642-9ba2-6f5bd446a62e.png)

**Comment by neffo** [comment]
Hmm, for some reason those images are wayyyy too small to start with. They should be 420x270, not sure why those values are being ignored. Do you have another extension that is compressing task bar?

**Comment by Etamuk** [comment]
> Do you have another extension that is compressing task bar?

No, I only have a few extensions. The only one regarding the panel is Dash to panel. 
To test I disabled all the extension, but Bing-wallpaper. 
The behavior is the same. 

Maybe it's because I am using an HiDPI-Screen (3840 x 2160 (16:9))?

**Comment by neffo** [comment]
Yeah that must be it, hmm. Sorry I assumed it was 1080p from the size of your screenshots.

**Comment by Etamuk** [comment]
Yes, I understand. But I always reduce the size to 50% before uploading it. Otherwise because of it's original size it is shown as huge image here ;-)

**Comment by neffo** [comment]
Haha yeah :) So this issue should be something we can deal with, I need to investigate the best/most reliable way to detect the scale factor that is affecting the indicator.

**Comment by Etamuk** [comment]
Thank you. Very nice.

**Comment by neffo** [comment]
This seems to have fixed it [82344e8](https://github.com/neffo/bing-wallpaper-gnome-extension/commit/82344e848f8830ced852b8531342991dcb97ee9a)

![image](https://user-images.githubusercontent.com/5569112/163800380-853c227e-c945-483a-93e3-0c4992a47e65.png)

**Comment by Etamuk** [comment]
That sounds good. I will have an eye on it :-)
