### ISSUE TITLE
[BUG] Hover over the wallpaper shows a black box

### ISSUE THREAD

**Issue by Camiropan** [neffo/bing-wallpaper-gnome-extension#171]
**Describe the bug**
When you move the mouse pointer over the image in the top menu bar, a black box appears instead of a focus effect.

**Screenshots**
![Bildschirmfoto vom 2022-05-16 17-08-59](https://user-images.githubusercontent.com/76531567/168624962-5de9eacd-93f7-49d1-8b83-ff1e0434e545.png)

**To Reproduce**
1. Click on Indicator in the top bar
2. Hover over the Wallpaper
3. See error

**Desktop:**
 - OS: fedora 36
 - Extension Version: 40
 - GNOME Version: 42.1

**Comment by neffo** [comment]
Does switching to 'dark style' in GNOME settings make any difference?

I don't see it in Ubuntu 22.04 with GNOME 42.0. (I have seen the bug myself, but haven't been able to reproduce it since an upgrade.)

**Comment by Camiropan** [comment]
no, the bug also exist in dark style.

**Comment by Camiropan** [comment]
I also tested Gnome OS with Gnome v43 alpha and the bug still exists.

**Comment by neffo** [comment]
I can confirm I am seeing it in Fedora 36 as well (but not Fedora 35). I think it might be a theme change, but really difficult to untangle where it's coming from. From my investigation it seems the CSS seems to have hover setting the background property to a solid color which might be overriding the image.

**Comment by Camiropan** [comment]
Ok... so maybe it depends on the Gnome version? (Because you don't have the issue with Gnome v42.0)
Anyway, let me know if i can help!

**Comment by neffo** [comment]
Ubuntu often does things differently, which is a thing I need to keep an eye out on (it's on my desktop). I test on another distros (Fedora and GNOME OS), but don't catch differences like this necessarily.

(The light and dark styles was another thing #153)

**Comment by neffo** [comment]
![image](https://user-images.githubusercontent.com/5569112/172053899-7e758fc7-bbf7-4e7d-a517-44836052888d.png)

A fix included in the PR #170 should fix this issue.

**Comment by Camiropan** [comment]
Thanks, i will check it when version 41 comes out :+1:

**Comment by hmenke** [comment]
I can reproduce.

![image](https://user-images.githubusercontent.com/1903556/194551710-0c49debd-15b0-4426-8010-b7740635d61e.png)

![image](https://user-images.githubusercontent.com/1903556/194551844-cfe8a100-bce2-454e-a07e-26dbd717cfca.png)

**Comment by neffo** [comment]
Can you check your extension version?

This should be visible on about page of the extension settings.

**Comment by hmenke** [comment]
I realize that I'm only on version 40. I will try with a later version again.

**Comment by neffo** [comment]
Ahh, right. Please advise if it's still occurring... but hopefully resolved with current version (v41).

**Comment by hmenke** [comment]
Indeed, no problems with version 43. Apologies for the annoyance.

**Comment by neffo** [comment]
All good mate, glad it's fixed :)
