### ISSUE TITLE
[BUG] Some photo in the indicator showed stretching such as 2022-08-14 bing photo

### ISSUE THREAD

**Issue by History-exe** [neffo/bing-wallpaper-gnome-extension#175]
>NOTE:
>GNOME will sometimes report errors associated extensions if you manually update them via the extensions website. These errors can be resolved by restarting GNOME shell (logging out and then back in again). If it's still creating errors, then please go ahead create an issue.

**Describe the bug**
About the indicator (maybe it called something else), some photo seems stretched in this interferce. Just as the picture shows below.
The stretched photo is [panther chameleon furcifer pardalis](https://www.todaybing.com/detail/1Rg98tGB.html)

**Screenshots**
Today's wallpaper seems stretched, but the wallpaper is fine.

_The streched picture in the indicator_
![2022-08-14 19-36-54 的屏幕截图](https://user-images.githubusercontent.com/33642965/184535565-e36c0e57-c295-4022-891f-465b10a9578c.png)

_The Wallpaper is fine_
![2022-08-14 19-55-39 的屏幕截图](https://user-images.githubusercontent.com/33642965/184535685-0b72fc99-fad5-485e-8ea9-8ab15b6eca4d.png)

**To Reproduce**
1. Turn on PC.
2. Click on the bing icon in the right up corner
3. See the stretched photo

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Extension Version: 41
 - GNOME Version: 3.36.8

**Additional context**
The stretch is just ok, but a little uncomfortable.

**Comment by neffo** [comment]
Yep, this is due to the additional text at the top of the menu. It's partly untranslated, which is probably making it worse.
