### ISSUE TITLE
[BUG] Recent changes on default gnome-shell theme make password entry box to be hardly readable

### ISSUE THREAD

**Issue by pacho2** [neffo/bing-wallpaper-gnome-extension#176]
**Describe the bug**
With latest gnome-shell default theme updates (I think they were introduced in Gnome 41 cycle), the password entry box was made transparent, that makes the box hardly readable when the extension is configured to get a fully transparent lock screen and a brilliant wallpaper is used.

Maybe the entry box theme could be tweaked back to safer transparency/color options :/

Thanks a lot

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Extension Version: 41
 - GNOME Version: 42

**Comment by neffo** [comment]
Yeah, it's not really ideal. Ultimately the extension isn't actually running when the lock-screen is active (that is possible but requires more hoops to jump through to get approval). I'm thinking of a few ideas but haven't come close to prototyping it. One option would be to split the extension so that we do the blur (and whatever features we want), but keep the code clean and easier to audit which is important for a lock-screen. Then it might be possible to inject a blurred backdrop to the login dialogs. Just an idea atm though.

**Comment by pacho2** [comment]
Maybe blur could be kept for the prompt screen. It seems it is the way gnome-shell-extension-unlockDialogBackground is handling this problem :thinking: 
https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground/blob/master/unlockDialogBackground%40sun.wxg%40gmail.com/extension.js#L74

**Comment by neffo** [comment]
That is a good idea, yeah.

In this case, it might be better for me to just advise people use the unlock dialog extension and remove this code from Bing Wallpaper.

**Comment by pacho2** [comment]
But that extension is different, is not as simple as https://github.com/PRATAP-KUMAR/control-blur-effect-on-lock-screen , it forces the user to set a "hard coded" image to be shown in the lock screen. Indeed, if I enable both, unlockdialogbackground extension will simply make lock screen to show a blue background is I don't manually set an image

**Comment by neffo** [comment]
Ok I have a working implementation of this now, feel free to test #189 if you are adventurous.

I'm comfortable with what we are doing, but two things of note.
Firstly, there's no transition, so it's a particularly abrupt (not Windows-like).

Secondly, we need to keep the Blur object active for this to work, which means we aren't disabling every part of the extension when the lockscreen is active. This isn't 100% compatible with EGO review guidelines seen [here](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#scripts-and-binaries). We could explicitly ask for the whole extension to remain active during both session mode in metadata, but would be problematic. An alternative would be to have this part of the extension separate from Bing Wallpaper. (It's something I considered, and may be forced when it gets reviewed.)

**Comment by neffo** [comment]
![image](https://user-images.githubusercontent.com/5569112/210773791-a3d60811-d7ac-4bcc-989b-d2a755d39b01.png)
![image](https://user-images.githubusercontent.com/5569112/210773827-187609d5-cf53-42b1-8439-dbbc817cf001.png)

**Comment by pacho2** [comment]
Sorry for the late reply, it works fine!

Thanks a lot
