### ISSUE TITLE
[BUG] v41 breaks custom theming, 

### ISSUE THREAD

**Issue by frosth555** [neffo/bing-wallpaper-gnome-extension#178]
the fix for #171 breaks accent color for all GS drom down menus.

tested on arc and whitesur themes. 

 - OS: ArchLinux OS
 - Extension Version: 41
 - GNOME Version: 42.4

it can be fix by simple remove [1] from stylesheet.css
[1]
"popup-menu-item:focus, .popup-menu-item:hover {
    background-color: rgba(247, 247, 247, 0.1) !important; }" 

screenshots:
after update bing extension to 41:
![after update bing extension to 41](https://user-images.githubusercontent.com/22305379/186891528-19451c34-9c5b-488b-872a-0eb16aa09d0c.png)

befor update or after remove [1]:
![befor update or after remove [1]](https://user-images.githubusercontent.com/22305379/186891932-0bd977d4-cd49-4a82-b198-46d82695291a.png)

after remove [1] thumbnails still look good
![after remove [1]](https://user-images.githubusercontent.com/22305379/186892624-e5bb3ed2-9dfb-44fb-b851-8ee05d1d37e4.png)

**Comment by neffo** [comment]
I'm not a CSS expert to be honest, so the issue is it is disabling the background highlight right? Is the thumbnail working with the CSS removed?

**Comment by frosth555** [comment]
thx, 
If you need some hands for testing tell me what is needed

I've checked fedora36/virt and it looks good.
