### ISSUE TITLE
Icon does not fit gnome theme

### ISSUE THREAD

**Issue by eevleevs** [neffo/bing-wallpaper-gnome-extension#18]
Prepared a replacement: ![bing](https://user-images.githubusercontent.com/5012744/31003083-474c3a58-a4dd-11e7-8454-e800f41c025a.png)

**Comment by neffo** [comment]
@eevleevs currently I'm using a .svg file so that it works with hidpi desktops, I'm not much of a designer can you tell me how the icon as is doesn't fit with the gnome theme? I presume colour?

**Comment by eevleevs** [comment]
In both colour and shape, looks like the icon must be square. See the difference, first is current:

![tis](https://user-images.githubusercontent.com/5012744/31044086-bc8f6b52-a5b7-11e7-8030-79c9c3cf3190.png)
![ti16](https://user-images.githubusercontent.com/5012744/31044073-6dacb17a-a5b7-11e7-84e5-c27f6c9a4126.png)

Here I updated colour and shape on the svg: [bing.svg.zip](https://github.com/neffo/bing-wallpaper-gnome-extension/files/1346252/bing.svg.zip)
