### ISSUE TITLE
changes to work with fedora 37 Beta

### ISSUE THREAD

**Issue by kflihan** [neffo/bing-wallpaper-gnome-extension#180]
Hi, 

I downloaded the code and changed the supported version by adding 43.rc to metadata.json

and removed the next  line from extention.js
   Soup.Session.prototype.add_feature.call(this.httpSession, new Soup.ProxyResolverDefault()); // unclear if this is necessary

and it works fine  :)

**Comment by neffo** [comment]
Thanks @kflihan, are new images being downloaded for you? I've been testing Fedora 37 and having some problems with the migration to Soup3.
