### ISSUE TITLE
Notifications not received

### ISSUE THREAD

**Issue by eevleevs** [neffo/bing-wallpaper-gnome-extension#19]
Although the setting is on

![image](https://user-images.githubusercontent.com/5012744/31053061-456357dc-a684-11e7-9ca5-c8fd1c311c80.png)

notifications do not appear on wallpaper change. Show description works. Ubuntu 16.04 with GNOME Shell 3.18.5. Available to test.

**Comment by neffo** [comment]
If you enable the indicator will the notification appear?

**Comment by neffo** [comment]
The indicator is visible I presume?

**Comment by neffo** [comment]
Ok, so this is probably due to the background image already existing on disk. This isn't quite right, I've got some new code which handles this better (if the background changes).

**Comment by eevleevs** [comment]
> The indicator is visible I presume?

Yes, the indicator is visible. Waiting to try the new code, let me know when published.

**Comment by neffo** [comment]
The updated version is currently in the review queue on the [GNOME extensions page](https://extensions.gnome.org), or you could try the zip file listed in the readme if you'd like to try it now.
