### ISSUE TITLE
[Feature Request] Use the blured image on Login Screen as well

### ISSUE THREAD

**Issue by Pawan-Johnson** [neffo/bing-wallpaper-gnome-extension#190]
I generally change my login screen using the following script.
https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background
Any chance we can incorporate this into this extension as well?

Right now, I was trying to work around by using the last image and blurring it and then passing it to the script.

**Comment by neffo** [comment]
Right, yeah not really possible to directly integrate it directly. (It's generally frowned up for extensions to call scripts.)

However, it would be possible to script it (perhaps have it in crontab) similar to what I've done [here](https://gist.github.com/neffo/69703cfc3251a0600b4f7e7149f7b109). I might hack something together, how are you blurring it?

**Comment by Pawan-Johnson** [comment]
At the moment I'm blurring it with a custom python script.
I tried that setting to change it seems quite specific to not allow images that are not in the /usr/share/background directory.

Attaching the script in case
```python

from PIL import Image, ImageFilter
import sys

def main(file_name):  
    
    # print(file_name)
    image = Image.open(file_name)
    
    # Cropping the image 
    # smol_image = image.crop((0, 0, 150, 150))
    
    # Blurring on the cropped image
    blurred_image = image.filter(ImageFilter.GaussianBlur(30))
    
    # Pasting the blurred image on the original image
    image.paste(blurred_image, (0,0))
    
    # Displaying the image
    image.save('blurred.png')

if __name__ == "__main__":
    file_name = sys.argv[1]
    # print(sys.argv)
    main(file_name)
```


P.S I presumed there was a blurred bundled with the extensions written in js?

**Comment by neffo** [comment]
The image blur is done by the GDM lockscreen itself, the image itself isn't blurred. (This extension allows you to change or disable the blur as well.)

This will make your script a bit easier to use:

```
from PIL import Image, ImageFilter
import sys
from gi.repository import Gio, GLib
from urllib.parse import urlparse

def main():  
    
    # get gnome settings object for desktop background
    background_settings = Gio.Settings.new("org.gnome.desktop.background")
    
    # get the URI of the image (which includes 'file://') and strip to just it's filepath
    file_name = urlparse(background_settings['picture-uri']).path
    #print(file_name)
    image = Image.open(file_name)
    
    # Cropping the image 
    # smol_image = image.crop((0, 0, 150, 150))
    
    # Blurring on the cropped image
    blurred_image = image.filter(ImageFilter.GaussianBlur(30))
    
    # Pasting the blurred image on the original image
    image.paste(blurred_image, (0,0))
    
    # Displaying the image
    image.save('blurred.png')

if __name__ == "__main__":
    # print(sys.argv)
    main()
```

**Comment by Pawan-Johnson** [comment]
Works like a charm. 
Thanks.
