### ISSUE TITLE
Button shapes need to be pressed exactly

### ISSUE THREAD

**Issue by zilexa** [neffo/bing-wallpaper-gnome-extension#192]
**Describe the bug**
Currently if I do not click exactly on the actual icon of a button, for example to "rewind" to a previous wallpaper, it is immediately a missclick and the window may close. Requiring me to repeat my steps and try again.

May I suggest to give each button a clickable area (circle or square), not necessarily a visible one? Because the button icons itself are tiny and especially on a laptop touchpad, it is difficult to click. I suppose with a more precise gaming mouse it would be less of an issue.

**To Reproduce**
1. Go to Bing wallpaper taskbar window
2. Click on prev/next/pause any of the buttons but click just slightly next to the actual white icon of the button (assuming dark mode)
3. Notice you have to click very precisely.

**Desktop (please complete the following information):**
 - OS: Manjaro Gnome
 - Extension Version: all
 - GNOME Version: 42

**Comment by neffo** [comment]
Thanks for great bug report, yes agree this is annoying. I have experienced the issue as well.

**Comment by neffo** [comment]
Couple of options, we can look at.

1. Making the icons larger, and setting icon style to true for both expand_x and expand_y. This looks like this (the position of the mouse pointer is roughly the extent of the clickable area for the '<' aka previous image button):
![image](https://user-images.githubusercontent.com/5569112/209842200-dc38ffa1-c063-4c86-abd1-91684c15be7b.png)
2. Replacing icons with discrete menu items themselves with text (we can still have icons as well) under a sub-menu (sometimes called a twistie). I don't know if I can maintain the clickable forward and back buttons, but we can use switches for 'shuffle' and 'switch to newest images'. Submenus look like this (I haven't mocked these up yet):
 
![image](https://user-images.githubusercontent.com/5569112/209841920-2a5a2a48-0c6d-4d15-9eff-74a86d57d569.png)

I'm kind of leaning towards the former for now, but we could include some quick settings in a submenu (and it's been something I've been considering for a while).

**Comment by zilexa** [comment]
I really like option 1. 
But option 2 (probably with less features than one) will probably look more "integrated" in Gnome 43 with its toggles so it's also attractive.

**Comment by neffo** [comment]
Yep, leaning towards option 1, but I think moving the toggles out to a submenu is good UX (atm it isn't clear that they are toggles or what they are toggling).
