### ISSUE TITLE
[Feature request] Favorite wallpapers

### ISSUE THREAD

**Issue by ndonkersloot** [neffo/bing-wallpaper-gnome-extension#196]
Hi there,

I really love the extension for a fresh wallpaper everyday, thanks for your efforts to maintain such extension!
I have a feature request for the extension. Sometimes there are wallpapers that I really like, and sometimes there are ones that I don't like.

I think it would be awesome if you could mark a wallpaper as a 'favorite' and make a toggle between the 'everyday a new wallpaper' or 'show only favorites'. This way you can easily revisit the ones you liked, even it is was a long time ago.

What do you think of this idea?

Best regards,

Nando

**Comment by neffo** [comment]
Thanks Nando, this is a great idea. Particularly when you collect a pretty sizable collection of wallpapers.

**Comment by neffo** [comment]
I like the idea enough that I'm already testing it:
![image](https://user-images.githubusercontent.com/5569112/216542191-a07ea1ce-bef0-49c2-b06c-38f0fc07d500.png)

**Comment by ndonkersloot** [comment]
Very very very cool, thank you so much :) .
