### ISSUE TITLE
Remove Watermark

### ISSUE THREAD

**Issue by Slomo17** [neffo/bing-wallpaper-gnome-extension#2]
This python scripts gets the Wallpaper without the watermark:
https://github.com/UtkarshGpta/bing-desktop-wallpaper-changer

Is it possible to implement this as well in this extension?

**Comment by neffo** [comment]
Hi Slomo17,

The watermark is include in images larger than 1920x1080 (ie 1920x1200). If you are running a lower resolution (eg. 1080), you should select change to that in the settings. Utkarsh's script autodetects your resolution, so it's likely you are running 1080p?

I haven't implemented resolution auto-detection or a drop down list of supported resolutions in the settings yet. And I haven't tested other resolutions extensively. It's possible you have encountered a bug if you have changed this setting.

**Comment by neffo** [comment]
@Slomo17 the new version i just uploaded to GNOME extensions should auto detect your resolution now.

(I am considering a bit of GEGL image handing to get around the Bing branding annoyance so stay tuned.)

**Comment by Slomo17** [comment]
Ah ok, good to know, thanks you very much. now the extension is perfect
