### ISSUE TITLE
In china, bing locale would not work very well

### ISSUE THREAD

**Issue by gwdgithubnom** [neffo/bing-wallpaper-gnome-extension#20]
I want use other country's bing image, but the request would always redirect to cn-zh. For more information: when i checked https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-us, and sometimes the response data would be like this:

{"images":[{"startdate":"20170930","fullstartdate":"201709301600","enddate":"20171001","url":"/az/hprichbg/rb/RedFlag_ZH-CN7582013591_1920x1080.jpg","urlbase":"/az/hprichbg/rb/RedFlag_ZH-CN7582013591","copyright":"国庆节期间街道上飘扬的五星红旗，中国深圳 (© Bartlomiej Magierowski/Alamy Stock Photo)","copyrightlink":"http://www.bing.com/search?q=%E5%9B%BD%E5%BA%86%E8%8A%82&form=hpcapt&mkt=zh-cn","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20170930_RedFlag%22&FORM=HPQUIZ","wp":false,"hsh":"dee45d124a9b85895f82ae27f80dc416","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"Loading...","previous":"Previous image","next":"Next image","walle":"This image is not available to download as wallpaper.","walls":"Download this image. Use of this image is restricted to wallpaper only."}}

This was same like the request url of https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-cn.

So, I give a solution to redirect to international edition bing.com. and code gives : https://github.com/agodomen/bing-wallpaper-gnome-extension.

And I have modify the notify function, let it would show the image of the url.

**Comment by neffo** [comment]
Ah... so this might be a quirk in how Bing handles the China market? If we added the **en-ww** market would it work reliably or would it have the same issues as using **en-US**?

**Comment by gwdgithubnom** [comment]
In that pull request code, I had verified it works well. And  I had  tried used VPN include jp, sgp, us, it also does well.

**Comment by neffo** [comment]
Ok @gwdgithubnom I've not merged your pull request directly, as I wanted to implement it a little bit differently. I've added a validation step to the extension preferences, and it will notify the user when the requested market doesn't match what was received.

**Comment by neffo** [comment]
@gwdgithubnom have you tried the current git version? do you have any feedback on it?

**Comment by cnyyk** [comment]
mbl=1 can't fix the problem, shown as below:

![WX20190406-133743](https://user-images.githubusercontent.com/275233/55665400-75a7f100-5871-11e9-8149-091e863b2137.png)
