### ISSUE TITLE
Click on a preview doesn't open default image viewer

### ISSUE THREAD

**Issue by QnuVGXic3n9H** [neffo/bing-wallpaper-gnome-extension#200]
**Describe the bug**
Click on the preview image doesn't open the default image viewer.

**Screenshots**
![bing wallpaper ext main window](https://user-images.githubusercontent.com/16448053/228328548-68fff99b-4306-4a6a-8734-43bfe48130d7.png)

**To Reproduce**
Click the Bing Wallpaper tray icon.
In the main window, click the wallpaper preview image.
The older version would open the default image viewer.
The current version closes the main window.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Extension Version: 44
 - GNOME Version: 43.1

**Additional context**
"Open in image viewer" menu does open default image viewer correctly

**Comment by neffo** [comment]
Yeah, I should probably bring that back. There is an explicit option in the drop down (twisty) just below the image which will open the image in an image viewer however.
