### ISSUE TITLE
[Feauture] Random gallery options seems too complicated

### ISSUE THREAD

**Issue by sabriunal** [neffo/bing-wallpaper-gnome-extension#206]
Random gallery options seems too complicated. We may use simple descriptions instead.

![Ekran Görüntüsü - 2023-05-23 17-21-05](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/6218679/babb4973-7485-47df-b877-6a3db55a46f7)

![Ekran Görüntüsü - 2023-05-23 17-28-19](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/6218679/f8fef7fd-0bb2-43cc-92fe-1a5a83bf14bf)

**Comment by neffo** [comment]
Agree, I think this is a better way. I've had to re-implement some of the code to fix the way shuffle mode worked (it was both weird and sort of broken), so this should be achievable.

**Comment by neffo** [comment]
![image](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/5569112/c14119c1-976b-402e-be24-3d97927c4f35)

Testing this in version 46 atm...
