### ISSUE TITLE
[BUG] Soap missing

### ISSUE THREAD

**Issue by balintbarna** [neffo/bing-wallpaper-gnome-extension#208]
**Describe the bug**
I get an error when I try to open the extension settings, both from extension manager and the status bar icon.

**Screenshots**
![image](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/13272850/ee806d63-b7d8-4b6f-a8f6-974e15e5c3f9)

**Desktop (please complete the following information):**
 - OS: openSUSE MicroOS Gnome
 - Extension Version: 45
 - GNOME Version: 44.1

**Additional context**
Log:
> The settings of extension ---@---.com had an error:
> ```
> Error: Requiring Soup, version 2.4: Typelib file for namespace 'Soup', version '2.4' not found
> ```
> 
> Stack trace:
> ```
> @/home/balint/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/prefs.js:12:48
> _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
> ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
> OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
> async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
> _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> start@resource:///org/gnome/gjs/modules/script/package.js:190:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

**Comment by Xathros1** [comment]
Opensuse MicroOS Desktop Gnome (now called Aeon), is coming by default already with typelib-1_0-Soup-3_0; if you'd temporarily install typelib-1_0-Soup-2_4 via t-u, this fixes it until a new version is released.

**Comment by neffo** [comment]
Yep, different distros appear to treat this differently. I mainly develop and test Ubuntu (I also test on Fedora). I believe this should be fixed in the PR #203  for the next version, but one option is to clone and install that version as well.

There are some fairly significant changes in that version, and I'm still working through making sure it all works.

**Comment by ddanneels** [comment]
On a fresh install of Debian Trixie, I was required to install libsoup2.4-dev to fix this error. (extension version 45)

**Comment by pacho2** [comment]
At least in version 46 I can see that the code looks adapted to libsoup-3 too... I would recheck if this is still valid, probably it was fixed
