### ISSUE TITLE
[BUG] Port extension to GNOME 45

### ISSUE THREAD

**Issue by neffo** [neffo/bing-wallpaper-gnome-extension#213]
This GNOME 45 will likely break compatibility with earlier versions of GNOME, and supporting GNOME 45 will likely require some remediation to fix in this extension:

https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by ttys3** [comment]
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by neffo** [comment]
Yeah, I've been putting this off (I'm on Ubuntu 23.04, so haven't moved to GNOME 45). Looking at it though, thanks for your patience!

**Comment by scottbeamer** [comment]
> Yeah, I've been putting this off (I'm on Ubuntu 23.04, so haven't moved to GNOME 45). Looking at it though, thanks for your patience!

This is why the good lord invented virtual machines. :)

Ubuntu 23.10 Beta and Fedora 39 Beta are out, both have GNOME 45 and both are pretty stable.

**Comment by IBBoard** [comment]
openSUSE Tumbleweed is also running Gnome 45 and is basically permanently stable (and a rolling release, _and_ has btrfs snapshotting built-in with a good management tool!)

**Comment by c3101** [comment]
+1

**Comment by neffo** [comment]
Apologies all been swamped with work, but will get this done asap. The wallpapers must flow.

**Comment by SeokYoung-Ahn** [comment]
It doesn't work on GNOME 45, I know you're busy, but please check. Please fix it. Thank you.

**Comment by ttys3** [comment]
currently I use a workaround : 

download executable from https://github.com/ttys3/Bismuth/releases/download/v1.0.0/bismuth-Linux-x86_64-musl.tar.gz

and install the user cron job:

```shell
git clone https://github.com/ttys3/Bismuth.git
cd contribute/systemd
./install.sh
```

not perfect, but things works

**Comment by greyltc** [comment]
I've tested https://github.com/neffo/bing-wallpaper-gnome-extension/pull/215 and it solves this issue for me. I've rolled that patch into [my package in the AUR](https://aur.archlinux.org/packages/gnome-shell-extension-bing-wallpaper) for the time being to get the wallpapers flowing for Arch Linux users.

**Comment by odror** [comment]
That workaround does not work for me on arch. Gnome still ignores the extension because it is not compatible with 45

**Comment by neffo** [comment]
Ok, I have a working version now. Massive thanks to @mcardillo55 for doing the heavy lifting. Please give him all the thanks for this. I've brought over some small fixes as well (from this branch #203 ), but please let me know how this works.

There are a lot of things I want to bring over from the other branch, but I want to get this version live ASAP. Thanks all for your patience.

**Comment by ivanjx** [comment]
it runs on gnome 45 but i cant seem to make it download the images

![image](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/12814796/203c3496-4e78-45fd-a997-7fd14a751067)

**Comment by neffo** [comment]
`Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: selected image changed to: current
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: getCurrentImageIndex for 202310200700: 811
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: getCurrentImageIndex for 202310200700: 811
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: Downloading https://www.bing.com/th?id=OHR.PygmySloth_ROW1074539359_UHD.jpg to file:///mnt/2t_btr1/BingWallpaper/20231020-PygmySloth_ROW1074539359_UHD.jpg
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: Storing state as JSON: {"maxlongdate":202310200700,"title":"Pygmy three-toed sloth baby, Isla Escudo de Veraguas, Panama","explanation":"Bing Wallpaper of the Day for 2023-10-20","copyright":"© Suzi Eszterhas/Minden Pictures","longstartdate":"202310200700","imageinfolink":"https://www.bing.com/search?q=sloth+animal&form=hpcapt&filters=HpDate%3a%2220231020_0700%22","imageURL":"https://www.bing.com/th?id=OHR.PygmySloth_ROW1074539359_UHD.jpg","filename":"/mnt/2t_btr1/BingWallpaper/20231020-PygmySloth_ROW1074539359_UHD.jpg","favourite":false}
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: getCurrentImageIndex for 202310200700: 811
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: selected image changed to: PygmySloth_ROW1074539359
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: /th?id=OHR.PygmySloth_ROW1074539359
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: Downloading https://www.bing.com/th?id=OHR.PygmySloth_ROW1074539359_UHD.jpg to file:///mnt/2t_btr1/BingWallpaper/20231020-PygmySloth_ROW1074539359_UHD.jpg
Oct 21 20:29:41 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: Storing state as JSON: {"maxlongdate":202310200700,"title":"Pygmy three-toed sloth baby, Isla Escudo de Veraguas, Panama","explanation":"Bing Wallpaper of the Day for 2023-10-20","copyright":"© Suzi Eszterhas/Minden Pictures","longstartdate":"202310200700","imageinfolink":"https://www.bing.com/search?q=sloth+animal&form=hpcapt&filters=HpDate%3a%2220231020_0700%22","imageURL":"https://www.bing.com/th?id=OHR.PygmySloth_ROW1074539359_UHD.jpg","filename":"/mnt/2t_btr1/BingWallpaper/20231020-PygmySloth_ROW1074539359_UHD.jpg","favourite":false}
Oct 21 20:29:42 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: scale factor: 2
Oct 21 20:29:42 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: image set to : /mnt/2t_btr1/BingWallpaper/20231020-PygmySloth_ROW1074539359_UHD.jpg
Oct 21 20:29:42 ubuntu-desktop-22 gnome-shell[66468]: BingWallpaper extension: Download successful`

Should be fixed @ivanjx , if you are grabbing directly form the PR do you want to try again?

**Comment by ivanjx** [comment]
works fine now. thanks @neffo

**Comment by neffo** [comment]
thanks @ivanjx 

I'll push this version to EGO, noting it probably has some bugs lingering.

There is a rewrite of the shuffle code in another branch, but I'm not 100% happy with it. So will leave that as is.

**Comment by IBBoard** [comment]
I'm sure it'll fix itself when EGO approves the newest version, but is anyone else finding that Gnome Extensions keeps "upgrading" to the old version of the extension (which then fails to load).

Annoyingly, it seems to do it without asking and just says "extensions will be upgraded when you log in again".

**Comment by neffo** [comment]
Yeah it'll keep downgrading, presumably to remove?

If you set the version to the same as the current approved (45) within metadata.json it may work.

**Comment by IBBoard** [comment]
> If you set the version to the same as the current approved (45) within metadata.json it may work without downgrading.

Yep, that seems to have done it!

Quick pointer for others, though: If it has already given you the "will be upgraded" message then log out, log in, let it "upgrade", re-extract, edit the version, log out and in to enable it, and it now thinks it has v45 but it's the version that works.

If you don't do that then you'll edit it to v45 and then it'll replace everything when you log out and back in!

**Comment by bklaas** [comment]
Confirmed working here on Endeavour(Arch) running Gnome 45
:1st_place_medal: :+1:
