### ISSUE TITLE
[BUG] Spanned syle not working as expected

### ISSUE THREAD

**Issue by tatephughes** [neffo/bing-wallpaper-gnome-extension#226]
When the option is set to 'Spanned' the image is stretched over the displays, rather than zooming to fill both displays without warping. I'm on a zenbook duo (dual screen laptop) and it makes the image look bad (although with different display setups I'd imagine spanning the wallpaper may look bad no matter how you do it). Hydrapaper seems to be able span images correctly on Gnome, so it is possible.

**Screenshots**
![Screenshot from 2024-01-14 12-38-58](https://github.com/neffo/bing-wallpaper-gnome-extension/assets/150016983/ec331490-4292-4f40-a663-70c5c3fb9ce0)

**To Reproduce**
1. Use multiple displays
2. Select 'Spanned' as the background style option

**Desktop:**
 - OS: Arch Linux
 - Extension Version: 48
 - GNOME Version: 45

**Comment by tatephughes** [comment]
Seems to have been fixed!

**Comment by neffo** [comment]
Oh? These settings are sort of hidden in GNOME now, and is expected to be removed in a future release. Did a restart fix it? All this preference does is change the GNOME setting, we actually don't really do anything unique :)
