### ISSUE TITLE
[BUG] Gnome Clock stops right after background image update

### ISSUE THREAD

**Issue by stefan-oskamp** [neffo/bing-wallpaper-gnome-extension#229]
**Describe the bug**
When the background image is updated, you can count to three and then the Gnome clock stops (seconds display enabled). The system clock is keeping time okay (e.g., date command in bash shows the right time).

This happens typically a couple of minutes after the machine has awaken from suspend mode. Eventually, the Gnome clock continues to run (i.e., without having to restart anything).

This happens every day.

**Journal entries**
Until ~10 seconds before the image update, there are lots of the following entries in the journal:

```
Mär 09 09:35:00 [...].lan gnome-shell[1782]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Mär 09 09:35:00 [...].lan gnome-shell[1782]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Mär 09 09:35:00 [...].lan gnome-shell[1782]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Mär 09 09:35:00 [...].lan gnome-shell[1782]: Object St.Button (0x5614a3ef0f10), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                               == Stack trace for context 0x56149e324800 ==
                                               #0   7fff6fa07c20 b   file:///home/stefann/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:597 (396d8496eba0 @ 51)
                                               #1   7fff6fa07ce0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:442 (396d8496e7e0 @ 579)
                                               #2   7fff6fa07dd0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:919 (396d8496f1a0 @ 1640)
                                               #3   7fff6fa07eb0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:343 (396d8496e4c0 @ 106)
                                               #4   7fff6fa09d60 b   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730 (112ff7291c40 @ 169)
                                               #5   56149e3ef1a0 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:761 (396d8496efb0 @ 380)
                                               #6   56149e3ef0f0 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:683 (396d8496ee70 @ 185)
                                               #7   56149e3ef068 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:651 (396d8496edd0 @ 15)
                                               #8   56149e3eefd8 i   resource:///org/gnome/shell/ui/init.js:21 (112ff7270ba0 @ 48)
Mär 09 09:35:00 [...].lan gnome-shell[1782]: Object St.Button (0x56149fb81920), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                               == Stack trace for context 0x56149e324800 ==
                                               #0   7fff6fa07c20 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:604 (396d8496ec40 @ 51)
                                               #1   7fff6fa07ce0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:443 (396d8496e7e0 @ 646)
                                               #2   7fff6fa07dd0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:919 (396d8496f1a0 @ 1640)
                                               #3   7fff6fa07eb0 b   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:343 (396d8496e4c0 @ 106)
                                               #4   7fff6fa09d60 b   resource:///org/gnome/gjs/modules/core/overrides/Gio.js:730 (112ff7291c40 @ 169)
                                               #5   56149e3ef1a0 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:761 (396d8496efb0 @ 380)
                                               #6   56149e3ef0f0 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:683 (396d8496ee70 @ 185)
                                               #7   56149e3ef068 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:651 (396d8496edd0 @ 15)
                                               #8   56149e3eefd8 i   resource:///org/gnome/shell/ui/init.js:21 (112ff7270ba0 @ 48)
```

Then, from the time of the update, about 30 of these:
```
Mär 09 09:35:10 [...].lan gnome-shell[1782]: Object .Gjs_ui_popupMenu_PopupBaseMenuItem (0x5614a2dffd80), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                               == Stack trace for context 0x56149e324800 ==
                                               #0   56149e3ef1b0 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:542 (396d8496e920 @ 395)
                                               #1   56149e3ef100 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:372 (396d8496e5b0 @ 116)
                                               #2   56149e3ef068 i   file:///home/stefan/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:1049 (396d8496f4c0 @ 45)
                                               #3   56149e3eefd8 i   resource:///org/gnome/shell/ui/init.js:21 (112ff7270ba0 @ 48)
```
Then, at about the time the Gnome clock stops, about 30 of these:
```
Mär 09 09:35:15 [...].lan gnome-shell[1782]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
                                               The offending callback was SourceFunc().
                                               == Stack trace for context 0x56149e324800 ==
                                               #0   56149e3eefd8 i   resource:///org/gnome/shell/ui/init.js:21 (112ff7270ba0 @ 48)
```

No more entries related to Gnome extensions after that.

**To Reproduce**
1. Wake the machine from suspend mode
2. Wait for the Bing Wallpaper extension to update the background (succeeds)
3. Watch the Gnome clock (seconds enabled) and count to three
4. Gnome clock stops

**Desktop:**
 - OS: Fedora 39
 - Extension Version: 48
 - GNOME Version: 45.4
 - Display: 4K, Wayland

**Additional context**
I do have a few other extensions installed.
Also, I cleaned up the image folder to see if it would improve the situation. Will update if it does.
I can send a log file extract by mail, if needed.

**Comment by stefan-oskamp** [comment]
I did not test that. I can try it during the next days.

**Comment by stefan-oskamp** [comment]
I shutdown my PC yesterday and booted it up today. After a few minute, the new background image was loaded and the issue did not occur. So it probably is related to suspend and wake-up.

I'm happy to try out changed code, if that helps.

The sequence of events that lead to the issue are:
1.  Screen is blanked after 10 minutes (no password lock, though)
2. Machine is suspended after 30 minutes
3. Next day, machine resumes after key press on keyboard. No password required.
4. After a few minutes, new background image is loaded and shown. This is at about 09:35:10 in above logs.
5. After a few seconds, the Gnome clock (with seconds display activated) stops. This was at 09:35:15 in the logs above. (As if the Gnome shell also suppresses callbacks needed for the clock.)

If you can advise me as to how to simulate loading a new background at any time, I would try out a few more combinations, e.g., suspending manually (without blanking the screen beforehand) and then load a new background, or loading a new background after the screen had been blanked and un-blanked.

**Comment by neffo** [comment]
The GNOME shell UI is single threaded run in that same thread, so when an extension blocks it blocks everything (partly why GNOME devs discourage them). The clock is in essence no different from a UI element from an extension. If that makes sense.

Thanks for your sequence there, my read is that the extension would be active the whole time (when suspended). Garbage collection could be cleaning up and breaking things. I don't know why it'd be impacting this extension in particular. I don't think I'm doing anything too unusual. I'll look into it further.

A work around might be to enable a lockscreen when returning from suspend.

**Comment by neffo** [comment]
Yeah, definitely not suggesting changing your workflow. (If it avoids the issue, would love to know though.)

**Comment by stefan-oskamp** [comment]
So, last night, I locked the desktop and let it suspend after that. This morning, when resuming from suspend, I unlocked the desktop. After about six minutes, it refreshed the background, and the Gnome clock stopped.

I then locked the screen again, waited a bit, and unlocked it. After that, the Gnome clock was running again.

**Comment by stefan-oskamp** [comment]
I possible found the culprit. Yesterday, I saw this log entry:
```
Mär 11 08:12:56 scinax.lan telegram-desktop[2221]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
```
So, I terminated Telegram before I let the PC go to suspend. And, indeed, the new background image was loaded this morning without any issues.

I will verify this once more, but I thought it could help you to understand the issue.

**Comment by stefan-oskamp** [comment]
The QT fake screen does not seem to cause this problem. I tested once more with no active QT application and the issue still occurred.

**Comment by stefan-oskamp** [comment]
The issue disappeared.

Not sure whether it's due to changes in newer Gnome versions or changes in this add-on, but the issue seems to no longer occur.

Besides the clock in the top bar, I have another add-on that shows an analog clock on the desktop. Initially both clocks stopped after each wallpaper update. Some time ago, the issue no longer showed for the Gnome clock in the top bar, and some time later, the issue also disappeared for the analog clock add-on. Therefore, I assume the root cause wasn't in the Bing background add-on.
