### ISSUE TITLE
Change Lock Screen wallpaper

### ISSUE THREAD

**Issue by llebegue** [neffo/bing-wallpaper-gnome-extension#23]
Hi,

I have just installed your extension from https://extensions.gnome.org/ . In the settings the update of the lock screen background is activated but refreshing the wallpaper doesn't change it.

Regards 
Ludovic

**Comment by neffo** [comment]
Hi Ludovic,

What distro and version are you running, and what display manager are you using? (LightDM or GDM)

**Comment by llebegue** [comment]
Hi
Yesterday was my first run of the extension.
It looks that it actually changes the  lock screen background but it uses the previous version of the background (that I didn't have yesterday because it was my first day).

So the status is

- wallpaper image is current bring.com image

- lock screen image is the previous day image

It looks ok to me... unless somebody wishes to synchronize the desktop wallpaper and the lock screen wallpaper.

For what it worth my distribution is Debian 9.3 and my display manager is GDM.

**Comment by neffo** [comment]
I am seeing this issue. Also, (somewhat unrelated) the extension now sets the lock screen password dialog background.

**Comment by neffo** [comment]
Ok, @llebegue so this looks like a bug in GDM. It's not updating to reflect the changed picture until reboot. The changes are being made correctly by this extension, but GDM isn't acknowledging it immediately. I'm looking into why...
