### ISSUE TITLE
[BUG] Very long uptimes result in black screens and log spam

### ISSUE THREAD

**Issue by TheWeirdDev** [neffo/bing-wallpaper-gnome-extension#236]
**Describe the bug**
When using the extension for long periods of time without restarting the shell or the OS, it starts to misbehave. Sometimes when I come back to my laptop, I see a lock screen with no background, and when I log in and try to change the background, nothing happens. The background stays black and empty. I also get a ton of error messages from this extension in the logs.

I disabled the 'Set Wallpaper' option and now I don't get the black screen anymore but the error logs persist, and I have to manually set the wallpaper every day.

**To Reproduce**
1. Use the extension normally for at least 7 days without a reboot/logout (you can suspend)

**Desktop:**
 - OS: `ArchLinux`
 - Extension Version: `49`
 - GNOME Version: Had this issue on both GNOME `45` and `46`

**Additional context**
This is the logs containing error messages:  [bing_ext.log](https://github.com/neffo/bing-wallpaper-gnome-extension/files/15303440/bing_ext.log)

**Comment by neffo** [comment]
Looks like something is being garbage collected that shouldn't be? Looks like the menu items themselves.

Locking/unlocking the screen should reload the extension and recreate those items, did that ever work?

**Comment by TheWeirdDev** [comment]
Lock screen did not affect the issue. The background on the lock screen was also black.

Anyways, I haven't seen this bug in the past month or so. I guess the latest version has fixed it. I'll close this one and open a new issue if I ever come across this bug again.
