### ISSUE TITLE
Bing Local stuck at Chinese-China

### ISSUE THREAD

**Issue by bukkit188** [neffo/bing-wallpaper-gnome-extension#24]
I try to change Bing Local to see if there is any different, but now i stuck at Chinese-China. I can't select any different Local because it doesn't show. Now i want to change back to English-International but i only see this.
![screenshot from 2017-12-18 11-48-38](https://user-images.githubusercontent.com/16435925/34090430-804b37b4-e3e9-11e7-863a-45f50d0b48ed.png)

**Comment by neffo** [comment]
@bukkit188 this one is a bit tricky to handle. I am assuming you are within mainland China? If you are within China if you select anything other than _Chinese - China_ or _English - China_ locale you will receive _China - Chinese_ locale data. This isn't a bug in this extension, it's the way Bing handles the China market.  See this issue here #20 for more details.

**Comment by neffo** [comment]
I wasn't able to test this myself, can I ask does _English - China_ work for you?

**Comment by bukkit188** [comment]
I'm from Viet Nam, not China. And i the drop-down list doesn't show anything except Chinese-China. I selected English-US (I think so) before and it working fine.

**Comment by bukkit188** [comment]
Checked issues #20 and seem like it's not the same as my problem.

**Comment by neffo** [comment]
Hmm, that is strange. (And sorry to assume you were from China.) That does seem like a bug, can you tell me what extension version you are running?

**Comment by bukkit188** [comment]
I'm using version 15 that showed on the photo below. The OS is Ubuntu 17.10. GNOME version is 3.26.2.
![image](https://user-images.githubusercontent.com/16435925/34213979-8df6dab2-e5d3-11e7-9c5e-544105aaa439.png)

**Comment by bukkit188** [comment]
Still waiting. Now i'm using your earth-view-wallpaper-gnome-extension as a replacement, it's very good.

**Comment by neffo** [comment]
Hi @bukkit188 I haven't been able to replicate this sorry. I always see the full list of locales/markets. I'm not sure how that could be happening.

One thing that may help me diagnose it, could you try typing this command after you open the extensions preferences:

`journalctl -e`

and copy and paste here any sections that seem relevant. There might be errors or warnings being generated that will help me understand the issue.

**Comment by bukkit188** [comment]
Sorry about the delay but it's here now.  My computer is in Vietnamese so "Thg 2 06 22:25:59" mean the month is February and day is the 6th. I hope you can fix it.
`Thg 2 06 22:25:59 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: JS WARNING: [/home/lenguyenhoangnhan/.local/share/gnome-shell/extensions/
Thg 2 06 22:25:59 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: JS WARNING: [/home/lenguyenhoangnhan/.local/share/gnome-shell/extensions/
Thg 2 06 22:25:59 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: Failed to load background 'file:///home/lenguyenhoangnhan/Pictures/BingWa
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11207]: JS LOG: Testing : https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11207]: JS LOG: fetching: https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 dbus[740]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='d
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 systemd[1]: Starting Hostname Service...
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 dbus[740]: [system] Successfully activated service 'org.freedesktop.hostname1'
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 systemd[1]: Started Hostname Service.
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: setup_framebuffers: assertion 'width > 0' failed
Thg 2 06 22:26:11 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11207]: JS LOG: Recieved 728 bytes
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.ControlCenter.SearchProvider'
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.Nautilus'
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.Calculator.SearchProvider'
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating via systemd: service name='org.gnome.Terminal' unit='gnome-ter
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 systemd[1371]: Starting GNOME Terminal Server...
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Calculator.SearchProvider'
Thg 2 06 22:26:47 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Nautilus'
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Terminal'
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 systemd[1371]: Started GNOME Terminal Server.
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 org.gnome.Nautilus[1388]: sys:1: PyGIWarning: Nautilus was imported without specifying a ver
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 org.gnome.Nautilus[1388]: sys:1: Warning: g_key_file_load_from_file: assertion 'file != NULL
Thg 2 06 22:26:48 lenguyenhoangnhan-Inspiron-5447 nautilus[11250]: Could not establish a connection to Tracker: Failed to load SPARQL backend:
Thg 2 06 22:26:52 lenguyenhoangnhan-Inspiron-5447 PackageKit[1227]: update-packages transaction /1009_eedcabca from uid 1000 finished with can
Thg 2 06 22:26:53 lenguyenhoangnhan-Inspiron-5447 PackageKit[1227]: resolve transaction /1010_bcdecaab from uid 1000 finished with success aft
Thg 2 06 22:26:53 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running search with refine-flags=require-icon with timeout=60 with max
Thg 2 06 22:26:54 lenguyenhoangnhan-Inspiron-5447 snapd[781]: 2018/02/06 22:26:54.351773 stateengine.go:98: state ensure error: decode new com
Thg 2 06 22:26:54 lenguyenhoangnhan-Inspiron-5447 PackageKit[1227]: new update-packages transaction /1011_edcecbaa scheduled from uid 1000
Thg 2 06 22:27:00 lenguyenhoangnhan-Inspiron-5447 PackageKit[1227]: update-packages transaction /1011_edcecbaa from uid 1000 finished with suc
Thg 2 06 22:27:00 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running refresh with timeout=60 with cache age=86400 on plugin=steam t
Thg 2 06 22:27:00 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running get-updates with refine-flags=require-update-details,require-u
Thg 2 06 22:27:03 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running get-updates with refine-flags=require-update-details,require-u
Thg 2 06 22:27:03 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running get-updates with refine-flags=require-version,require-update-d
Thg 2 06 22:27:03 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running get-distro-updates with refine-flags=require-version,require-s
Thg 2 06 22:27:03 lenguyenhoangnhan-Inspiron-5447 gnome-software[1803]: running refine with refine-flags=require-version,require-update-detail
Thg 2 06 22:27:10 lenguyenhoangnhan-Inspiron-5447 gnome-terminal-[11253]: Allocating size to GtkBox 0x5641824ee6f0 without calling gtk_widget_
Thg 2 06 22:27:10 lenguyenhoangnhan-Inspiron-5447 gnome-terminal-[11253]: Allocating size to GtkBox 0x5641824ee6f0 without calling gtk_widget_
Thg 2 06 22:28:22 lenguyenhoangnhan-Inspiron-5447 Web Content[2195]: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission deni
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: last_user_time (12164534) is greater 
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: 0x2400154 (Bing Local) appears to be 
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: last_user_time (12164564) is greater 
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: 0x2400154 (Bing Local) appears to be 
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: last_user_time (12164864) is greater 
Thg 2 06 22:28:52 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: 0x2400154 (Bing Local) appears to be 
Thg 2 06 22:28:53 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: last_user_time (12165766) is greater 
Thg 2 06 22:28:53 lenguyenhoangnhan-Inspiron-5447 org.gnome.Shell.desktop[1454]: Window manager warning: 0x2400154 (Bing Local) appears to be 
Thg 2 06 22:30:12 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11433]: JS LOG: Testing : https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:30:12 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11433]: JS LOG: fetching: https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:30:12 lenguyenhoangnhan-Inspiron-5447 dbus[740]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='d
Thg 2 06 22:30:12 lenguyenhoangnhan-Inspiron-5447 systemd[1]: Starting Hostname Service...
Thg 2 06 22:30:13 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: setup_framebuffers: assertion 'width > 0' failed
Thg 2 06 22:30:13 lenguyenhoangnhan-Inspiron-5447 dbus[740]: [system] Successfully activated service 'org.freedesktop.hostname1'
Thg 2 06 22:30:13 lenguyenhoangnhan-Inspiron-5447 systemd[1]: Started Hostname Service.
Thg 2 06 22:30:13 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11433]: JS LOG: Recieved 728 bytes
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.ControlCenter.SearchProvider'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.Nautilus'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.Calculator.SearchProvider'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.Calendar'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Activating service name='org.gnome.seahorse.Application'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Calculator.SearchProvider'
Thg 2 06 22:30:28 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Thg 2 06 22:30:29 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Nautilus'
Thg 2 06 22:30:29 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.Calendar'
Thg 2 06 22:30:29 lenguyenhoangnhan-Inspiron-5447 dbus-daemon[1388]: Successfully activated service 'org.gnome.seahorse.Application'
Thg 2 06 22:30:29 lenguyenhoangnhan-Inspiron-5447 org.gnome.Nautilus[1388]: sys:1: PyGIWarning: Nautilus was imported without specifying a ver
Thg 2 06 22:30:31 lenguyenhoangnhan-Inspiron-5447 gnome-tweak-tool.desktop[11563]: WARNING : Error loading desktopfile: /home/lenguyenhoangnha
Thg 2 06 22:30:39 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11594]: JS LOG: update_globe() -> imagedata: County Road 431, Colby, Morgan,
                                                                          39.3753N, 100.9832E|©2016 DigitalGlobe|39.375301|-100.983196|17 
                                                                           bbox: -180,80,180,-50 marker: 39.375301%2C-100.983196 html: <html s
Thg 2 06 22:30:43 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11646]: JS LOG: Testing : https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:30:43 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11646]: JS LOG: fetching: https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:30:44 lenguyenhoangnhan-Inspiron-5447 gnome-shell[1454]: setup_framebuffers: assertion 'width > 0' failed
Thg 2 06 22:30:44 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11646]: JS LOG: Recieved 728 bytes
`

**Comment by neffo** [comment]
Hi @bukkit188, could you post the full lines for these:

```
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11207]: JS LOG: Testing : https://www.bing.com/HPImageArchive.aspx?format=js
Thg 2 06 22:26:10 lenguyenhoangnhan-Inspiron-5447 gnome-shell-ext[11207]: JS LOG: fetching: https://www.bing.com/HPImageArchive.aspx?format=js
```

It's not showing the full URL unfortunately.

**Comment by MalcolmMielle** [comment]
I can reproduce this. I've had the list once and no I'm stuck at Slovenia because of a misclick :P

**Comment by bukkit188** [comment]
I'm sorry but i had to move to windows because of my job, so i can't send you any information, but i hope this thread help, and maybe MalcolmMielle can reproduce it, she/he can help you.
Thks neffo for the beautiful extension.
