### ISSUE TITLE
[BUG] No GNOME 47 support

### ISSUE THREAD

**Issue by cedricroijakkers** [neffo/bing-wallpaper-gnome-extension#245]
**Describe the bug**
GNOME 47 has been released in the Arch repo's but the extension is marked as outdated.

**Screenshots**
N/A

**To Reproduce**
Install GNOME 47
Install this extension

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Extension Version: 49
 - GNOME Version: 47

**Additional context**
N/A

**Comment by cedricroijakkers** [comment]
> download https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw If you don't have the c compliator, install it.(gcc or clang)

Is this the new way of spamming? I got the exact same comment when creating another bug in Github.
No, I will not download your dodgy source code from META and compile it, thank you very much.

**Comment by cedricroijakkers** [comment]
PS: The extension works fine if you add support for version 47 in `~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/metadata.json`, it just needs a new release.

**Comment by neffo** [comment]
Not sure who posted the link originally but please don't repost without censoring

**Comment by neffo** [comment]
> PS: The extension works fine if you add support for version 47 in `~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/metadata.json`, it just needs a new release.

Yes this should be a fairly straight forward release to support GNOME 47, we've got a test branch #242 with support but I need to test with before I upload it. Hopeful to get that done this weekend. Thanks for your patience and bug report, once this is released this issue will be closed :)

**Comment by cedricroijakkers** [comment]
Confirmed that the auto-update at 9:05 this morning worked flawlessly.
