### ISSUE TITLE
use XDG Picture directory instead of ~/Pictures/BingWallpaper by default

### ISSUE THREAD

**Issue by Tids** [neffo/bing-wallpaper-gnome-extension#25]
At first let my say THANK YOU for this extension. Since my switch from KDE Plasma i was missing the Bing Picture source wallpapers and you just solved this.
However there is one thing that I noticed.

By default you save the wallaper to ~/Pictures/BingWallpaper, since not everyone is LANG=C, this directory is not available for everyone. Could you "localize" that picture directory? You can get the actual directory by using

```xdg-user-dir PICTURES``` 

(wich would output `/home/fabian/Bilder` for me)

in a shell. Sadly I dont know how to make this work for your extension :(

**Comment by neffo** [comment]
@Tids thanks, this is a good point. And thanks for using the extension!

I believe the extension will create that directory ~/Pictures/BingWallpaper including parent directories, but it's very messy to be creating directories in the home folder... and we shouldn't assume English!

`
let dir = Gio.file_new_for_path(BingWallpaperDir);
if (!dir.query_exists(null)) {
    dir.make_directory_with_parents(null);
}
`

I will investigate a fix.

**Comment by neffo** [comment]
@Tids this should now be fixed in this repo, but it will take some time for this to propagate into the live version of the extension on the gnome website

In the meantime you can change this manually in the extension preferences.
