### ISSUE TITLE
Extension sets background to solid color (not bing image)

### ISSUE THREAD

**Issue by Hergeirs** [neffo/bing-wallpaper-gnome-extension#26]
I just started experiencing this yesterday when my background suddenly was solid blue. I thought it might be a onetime issue, but today the background changed to solid white.

Description mentions some kind of mushroom.
![image](https://user-images.githubusercontent.com/20126436/35131408-e8fb2fde-fcbd-11e7-9b49-14dc577a49e8.png)

So I cheked the url, which leads to the correct image:
https://bing.com/az/hprichbg/rb/BlueMushroom_EN-US9252668987_1920x1080.jpg

By the way love the extension it's so nice and simple to use. 

EDIT:
OS     : Arch Linux x86_64
Kernel: 4.14.13-1-ARCH
Gnome Shell 3.26.2

**Comment by aw73** [comment]
Hi. Since yesterday I'v got the same issue.

OS: Antergos 
Kernel: x86_64 Linux 4.14.13-1-ARCH
GNOME Shell 3.26.2

**Comment by cedricziel** [comment]
Came here to say the same :)

**Comment by Bartwillemsen** [comment]
Yeah noticed this as well. It looks like the addon malforms the downloaded image for some reason. When I try to view the image it displays the following warning: 

![afbeelding](https://user-images.githubusercontent.com/1550822/35141171-63a9d122-fcfa-11e7-9d69-a2dc9fb8919e.png)

**Comment by pszafer** [comment]
Same for me.
Extension is downloading part of html document in front of image.
If you delete firts five lines than jpg is rendered correctly.

~~~
><head><title>Object moved</title></head><body>^M 
<h2>Object moved to <a href="https://www.bing.com:443/az/hprichbg/rb/OldTownPrague_ROW10740197540_1920x1080.jpg?toWww=1&amp;redig=E92A6BA01F5D468DA2D41AD6571DB27E">here</a>.</h2>^M 
</body></html>^M 
~~~

Reading this header and what 'copy URL to clipboard' returning to me.
I changed your code from

~~~
const BingURL = "https://bing.com";
~~~

to 

~~~
const BingURL = "https://www.bing.com";
~~~

and it is working again

**Comment by Bartwillemsen** [comment]
Oh, good work ^^ Maybe make a pull request for the fix?

**Comment by pszafer** [comment]
Done https://github.com/neffo/bing-wallpaper-gnome-extension/pull/27

**Comment by neffo** [comment]
Thanks everyone, great work! I'm merged the pull request.
