### ISSUE TITLE
Update of the picture leaves an empty background

### ISSUE THREAD

**Issue by tlogynd** [neffo/bing-wallpaper-gnome-extension#29]
Hello,
since 17th January the extension only changes the wallpaper to a monochrome background. It's completely blue or black, whatever the main colour of the wallpaper. Can you help me?

**Comment by xfarret-gpsw** [comment]
Hello,
I have the same problem. It seems that an html page is returned instead of the image itself.
In this html page we can see "Object moved to here". Then if you click on the link you can download the picture.
But what is surprising me is when you invoke directly in a browser the url https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=<market> : 
- you get the correct json response
- url value is valid (if you try it in a browser also, you get the picture)

Thanks in advance if you find the issue.

**Comment by Tahini-123** [comment]
Same problem here. Only had the black background so far. The images downloaded seem somehow corrupted starting from 17.1.2018. They wont open with image processing software, and return instead '_Error interpreting JPEG image file (Not a JPEG file: starts with 0x3c 0x68)_'.

**Comment by jgout** [comment]
Same here!

**Comment by neffo** [comment]
Hi all, sorry about this bug. Bing changed their config to include a redirect, that resulted in the this extension breaking. I'm not sure why Soup is is handling it so weirdly. A fix is in this repo, but hasn't been pushed out to extensions.gnome.org. (See also: #26, #28)

I will leave this issue open until the fixed version is live on the GNOME website.

**Comment by neffo** [comment]
As a temporary work around (for those not using the git version):

1. Open the file "~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js" in a text editor
2. Find the line (should be line number 25) that says: const BingURL = "https://bing.com";
3. Change it to: const BingURL = "https://www.bing.com";
4. Then press Alt-F2, type 'r' and press enter. 
5. Delete the broken image from your BingWallpaper folder (for most people this will be ~/Pictures/BingWallpaper/) and force a refresh to get it to download the correct image.

**Comment by IBBoard** [comment]
I seem to be getting the web page prepended to the front of the image. If you hex edit the file to remove the HTML and leave it starting with "FF D8 DD E0" then it'll refresh and show the image after a couple of seconds.

Or just apply the patch/wait for the update, obviously!

**Comment by neffo** [comment]
Yeah, Soup is following the redirect to www.bing.com, but the data from bing.com is also being included in the saved data. This is because we aren't checking the response correctly in the headers and confirming 200 before we start saving the data to disk. Whoops.

**Comment by angelsclare** [comment]
Error interpreting JPEG image file (Not a JPEG file: starts with 0x3c 0x68) 一直出现这个报错,Ubuntu16

**Comment by neffo** [comment]
Does anyone know anyone with GNOME extension approval powers? Nobody seems to be approving updates at the moment, and I can't get a response in the GNOME irc channel...

![](https://media.giphy.com/media/5xtDarEbygs3Pu7p3jO/giphy.gif)

**Comment by timmillwood** [comment]
Thanks @neffo keep up the good work!

**Comment by neffo** [comment]
Hi all,

Version 18 is now live on the GNOME extensions page, please update if you haven't installed the Git version.
