### ISSUE TITLE
Today's image not loading

### ISSUE THREAD

**Issue by timmillwood** [neffo/bing-wallpaper-gnome-extension#33]
My wallpaper is black, and when opening the file it says `Error interpreting JPEG image file (Not a JPEG file: starts with 0xef 0xbb)`.

**Comment by alexislefebvre** [comment]
I think that it was an error from Bing, since the background of bing.com was black last night (I checked when I had a black wallpaper like you).

**Comment by neffo** [comment]
Yeah we should probably be checking that the file is a valid JPEG file before saving and setting. The extension is pretty aggressive in refreshing the wallpaper, it's usually updated within 5 minutes of Bing's scheduled update (if your computer is on).

We had an issue previously (#29) where there was a redirect that we weren't following correctly. @timmillwood, if you can look at the file in a hexeditor, please let me know if you can identify the problem (or paste an image here if you want). Last time the initial page from the redirect was being included in the file.

What you are seeing there is a [UTF-8 file signature](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8), so it's possible you are getting a HTML file (or even text file, perhaps JSON) returned.

(Bing sometimes does some fancy things like animated backgrounds, which we should handle correctly - but they might have been trying something new we don't handle.)

It's not unheard of for Bing or Microsoft to break things...

![buyhimout](https://user-images.githubusercontent.com/5569112/38733003-a9901cd6-3f63-11e8-83ae-cbc4f9401047.gif)
