### ISSUE TITLE
Language list should be sorted

### ISSUE THREAD

**Issue by rugk** [neffo/bing-wallpaper-gnome-extension#36]
As far as I see, Germany is not in the list of languages you can select. However, Bing of course has special wallpapers for Germany.

**Comment by neffo** [comment]
What do you see in the locale list? Are you missing items?

![image](https://user-images.githubusercontent.com/5569112/39674844-adfd8292-5195-11e8-9b74-06ee147c5d58.png)

**Comment by rugk** [comment]
Uh, LOL, indeed. Did not notice it there.

Maybe the real issue is that I searched for it alphabetically, but the placement is very strange: A, B, C, D, **G**, E – so uh??

So i change this issue. Use it to sort the language list, otherwise it confuses users.

**Comment by neffo** [comment]
It's actually sorted by the locale/market codes which the user doesn't see, so it's a bit awkward, i.e. "German - Germany" is "de-DE".

We could sort by the English name, but that seems a bit English-centric, and having the whole list translatable would be a real pain. What I'd rather do is use the native languages here, as in "Deutsch - Deutschland" and keep the original sorting. I wasn't able to find complete list for this however...

**Comment by neffo** [comment]
Ok, I've done both:

![image](https://user-images.githubusercontent.com/5569112/39684641-ae94adf0-5200-11e8-91a9-fc9d08c7c17f.png)

If you want, you can check this out using the latest git version.

**Comment by rugk** [comment]
IMHO as it is translated, prepednding the ISO code is not useful. Eversbody knows their iso code, but it is kinda useless to display it.
