### ISSUE TITLE
Two monitors

### ISSUE THREAD

**Issue by duncio** [neffo/bing-wallpaper-gnome-extension#38]
I'd love to see an option to set bing wallpaper only on one monitor on a multiscreen setup.
Thanks

**Comment by neffo** [comment]
I'm actually not sure this is possible through the functionality that GNOME offers. It would probably be possible to do it for workspaces (see this [extension](https://github.com/BlinkBP/walkpaper)), so something like [nitrogen](https://github.com/l3ib/nitrogen) might be better. I broke my second monitor a while ago, so I haven't looked into two screen solutions as yet.

I'd rather not introduce too much complexity with dealing with external programs, but it's possible nitrogen could be extended to use the GNOME wallpaper DConf setting for one of the desktops...

**Comment by mr-gosh** [comment]
indeed the bing extesion overwrites the gnome tweaks setting how the backround should be handled.
I set the rendering method to "spann" but after each background update it is reset to "zoom"

**Comment by mr-gosh** [comment]
From my perspective this shouldn't be changed if the user changed it own his own - but presenting an option that makes it possible for the user to use the best fitting option based on the used background image would be awesome.
I think the selected option is based on the content of the Image that is used - so this would differ from image to image and user to user.

**Comment by neffo** [comment]
Bumping this, and noting that this seems to indicate we might be able to support changing wallpapers by monitor. Will look into this when I have two monitors to test this.

https://github.com/GNOME/gnome-shell/blob/master/js/ui/background.js

**Comment by cubanp3te** [comment]
I'm using a temporary workaround across 3 monitors (portrait) as follows:
1. Go to `~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com`
2. Open _extension.js_ in a text editor
3. Edit line 65:
    - from: `gsettings.set_string('picture-options', 'zoom');`
    - to: `gsettings.set_string('picture-options', 'spanned');`
4. Restart Gnome Shell (ALT+F2, r <return>) / Or Logout and back in

Any time the extension loads a new wallpaper it will be spanned across your 2+ screens

**Comment by neffo** [comment]
I've added a patch that hopefully fixes this one to the upcoming version 37, so this is configurable in prefs.
