### ISSUE TITLE
Description is not updated at midnight

### ISSUE THREAD

**Issue by alexislefebvre** [neffo/bing-wallpaper-gnome-extension#39]
When my computer is turned on while entering a new day, wallpaper is updated shortly after midnight but the description in the menu bar is not updated and show description of yesterday's wallpaper.

**Comment by alexislefebvre** [comment]
But the description is updated after manually triggering a refresh.

**Comment by neffo** [comment]
Looks like a bug was introduced while trying to work around the GNOME shell crash bug #17. Menu updates should occur now. Seems to have fixed it on my machine.

![image](https://user-images.githubusercontent.com/5569112/43686674-271402be-990d-11e8-9c1b-4ae00ca4b8eb.png)

**Comment by alexislefebvre** [comment]
I cloned the extension in order to get the new version and the description has been updated successfully. Thanks!

**Comment by alexislefebvre** [comment]
It looks like the problem is here again. Wallpaper was updated but the description was the one from yesterday.

**Comment by neffo** [comment]
Hmm, I'll need to take a deeper look at this. Bear with me.

**Comment by alexislefebvre** [comment]
Last update has fixed the issue.

Thanks
