### ISSUE TITLE
Doesn't show on desktop

### ISSUE THREAD

**Issue by dragonbite** [neffo/bing-wallpaper-gnome-extension#4]
For some strange reason I only see the bing picture when I open the Activities (dash?) screen.  Otherwise it shows a solid color for the background.

Also, when I try to go into settings I get the following error message instead of a window of any kind.

`Gtk.BuilderError: /home/drew/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/Settings.ui:26:1 Required gtk+ version 3.20, current version is 3.18

Stack trace:
  buildPrefsWidget@/home/drew/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/prefs.js:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1
  `
This occurs whether I try from the top panel button, Gnome Tweak or the web.

I am running Ubuntu Gnome 16.04, my screen is maxed out at 1366x768 in case that is the issue.  Clicking Background in the Settings shows the Bing wallpaper.

Any help is appreciated! Thanks!

**Comment by dragonbite** [comment]
Nevermind. I just read the rest of the Error message which says "Required gtk+ version 3.20, current version is 3.18" 

Does anybody know which version of gtk+ is in 17.04?

**Comment by neffo** [comment]
@dragonbite I have libgtk2 v2.24.31 and libgtk-3 v3.22.11 on Ubuntu 17.04, but I may have some GNOME PPAs which have newer versions than shipped.

What do you see when you type this?
`dpkg -l libgtk-3-bin`

**Comment by neffo** [comment]
@dragonbite OK so Ubuntu 16.04 ships with gtk3 v3.18, this should be fixed in the next release.

Regarding the strange issue with the background only being visible in overview, does it do the same with other wallpapers? Do you have icons on your desktop?

**Comment by dragonbite** [comment]
Thank you for your quick reply.

I have used Variety previously for rotating my background from wallpapers I've downloaded.  I made sure i turned Variety off and set it to not auto-start.  I do have icons on the desktop.

When I ran the dpkg command I got the following output.  It looks like the issue may be even with libgtk because it has the line 

> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)

So it may be a bigger issue than anticipated.
`drew@Goblin:~$ dpkg -l libgtk-3-bin
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  libgtk-3-bin        3.18.9-1ubuntu amd64          programs for the GTK+ graphical user interf
drew@Goblin:~$ `

**Comment by neffo** [comment]
@dragonbite are you still getting this problem?

The reason I asked about icons, is that if you do nautilus is running. If Nautilus is confused that might explain why you see the wallpaper in overview, but not when in normal desktop mode. (I don't have icons on my desktop, so I haven't seen this issue.)

**Comment by dragonbite** [comment]
I'm not ignoring you.  I have been out camping for the past week+.

I'll try to take a look at this tonight.  Just wanted to let you know I have not disappeared.

**Comment by Alfro** [comment]
Hi! I am having a similar issue (only see the bing picture when I open the Activities (dash?) screen), but in my case, I don't have any error messages when opening the extension settings.

 @neffo It is Nautilus! I do have icons on my desktop (and I was unaware that it's Nautilus the one that renders them), so I did a `ps aux | grep nautilus` and there it was:
`
alfro    18714  0.1  0.4 1132044 81048 ?       Sl   15:24   0:08 /usr/bin/nautilus --gapplication-service
`
So, if I kill it, the background appears correctly (but no icons, of course)

**Comment by Alfro** [comment]
I figured out what the issue seems to be. Let's look at the possible values of **gsettings get org.gnome.desktop.background picture-uri** when I use the extension vs when I use the settings GUI.

GUI (Desktop shows correctly):
`'file:///home/alfro/Pictures/20170809-HydricHammock_ROW8394414697_1920x1080.jpg'`
Extension (Desktop goes to default correctly):
`'/home/alfro/Pictures/20170809-HydricHammock_ROW8394414697_1920x1080.jpg'`

As the value is called "picture-uri" and not "picture-file", I guess it makes sense? Kinda?
I'm doing a PR.

**Comment by Alfro** [comment]
Done.  At least now it works for me! :D

Suggestions and feedback are welcome.

**Comment by neffo** [comment]
Thanks Alfro, your pull request has been merged. Thanks for doing the detective work on the bug!

**Comment by neffo** [comment]
This fix will be in version 9 of the extension on [extensions.gnome.org](https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/), currently in the approval queue.
