### ISSUE TITLE
Setting Chrome Background

### ISSUE THREAD

**Issue by nournia** [neffo/bing-wallpaper-gnome-extension#43]
Hi,
It would be great if this extension could change chrome background.
Thanks a lot.

**Comment by neffo** [comment]
Hi Nournia,

Can you expand on this feature request a little bit? Do you mean the chrome/chromium browser?

**Comment by nournia** [comment]
Latest version of Chrome browser has a new feature for customizing background image on new tab page. Bing wallpapers are great and thanks to this extension I enjoy seeing them on my desktop. I hope to see them on chrome new tab page.

**Comment by neffo** [comment]
Hi Nournia, this is something that'd best be handled by a Chrome extension. From what I gather Chrome extensions are written in JS, so some code could be reused between this Gnome extension and a Chrome extension. I personally use Firefox however. :fox_face: 

This sounds like it'd be a fun project though. Let me know if there's an existing extension that does this sort of thing, I'd like to take a look.
