### ISSUE TITLE
Wallpapers downloaded twice

### ISSUE THREAD

**Issue by wytesk133** [neffo/bing-wallpaper-gnome-extension#45]
![screenshot from 2018-12-09 19-51-45](https://user-images.githubusercontent.com/3948279/49710116-7ba40300-fbec-11e8-9061-075b66bd5c60.png)

As you can see in the picture, some wallpapers are downloaded the second time with "th?id=OHR." prefix.

**Comment by neffo** [comment]
Thanks for the report, I'll look into it.
