### ISSUE TITLE
Light series Gnome-shell theme icon color depth

### ISSUE THREAD

**Issue by Hentioe** [neffo/bing-wallpaper-gnome-extension#46]
This is a dark theme:
![image](https://user-images.githubusercontent.com/13946976/50710472-15ed4e80-10a6-11e9-8a89-88e33e22113f.png)

This is a light theme:
![image](https://user-images.githubusercontent.com/13946976/50710482-1dacf300-10a6-11e9-9c36-358520978bcd.png)

On the light series theme, should the icon be darker?

**Comment by neffo** [comment]
#61
