### ISSUE TITLE
Show a notification containing the title and the explanation of the image

### ISSUE THREAD

**Issue by shbach** [neffo/bing-wallpaper-gnome-extension#50]
Would it be possible to add the option of showing a notification containing the title and the explanation of the image? The NASA APOD extension implements this well and it seems this one is based off that so maybe it wouldn't be too difficult to add.

**Comment by mcardillo55** [comment]
There normally is (see picture). But it currently isn't showing due to #48 

![Screenshot from 2019-04-25 22-10-11](https://user-images.githubusercontent.com/2712861/56784908-c98a6380-67a7-11e9-804c-64ff6ab6643b.png)

**Comment by shbach** [comment]
That's not the notification I was referring to. See [this image](https://extensions.gnome.org/extension-data/screenshots/screenshot_1202_EBcSaHw.png). I'm referring to a temporary notification that pops up when the wallpaper changes and contains the description of the image (the paragraph or so description that Bing provides, not just the title).

The option available in the NASA APOD extension:
![Screenshot from 2019-04-26 09-35-54](https://user-images.githubusercontent.com/5298745/56823203-0ede7d80-6808-11e9-8ca1-5e02e2573109.png)

Ideally the text below would be contained in the notification:
![Screenshot from 2019-04-26 09-47-53](https://user-images.githubusercontent.com/5298745/56823362-7d234000-6808-11e9-9eb6-9d0366098940.png)

**Comment by neffo** [comment]
This was originally a feature, but I ended up removing it. If you use the locale of your region the popups would appear either at start up or at midnight. I didn't think they added much value, but I find popups a bit annoying :) They were causing some issues as a result of an unrelated GNOME bug at one point, and they took some of the blame for that too.

It would be possible to add these back, the codebases have diverged a little bit, but are fundamentally pretty similar. Happy to accept patches, especially if someone wants to come up with a clever way to show these.

**Comment by neffo** [comment]
Just an update to this, the text provided by the API is only the description, and the title ("Happy Arbor Day!" in  your example above).

I wouldn't know how to fetch this text without going deeper into Bing's APIs.

**Comment by shbach** [comment]
> Just an update to this, the text provided by the API is only the description, and the title ("Happy Arbor Day!" in your example above).
> 
> I wouldn't know how to fetch this text without going deeper into Bing's APIs.

Since the NASA APOD extension is able to fetch that text, would looking at that help in figuring it out?

I agree that popups could potentially be annoying so the option to turn it off would be good. Honestly though if that is too much of a hassle to implement, what I mostly wanted was that detailed description text when clicking on the icon. Sometimes I want to read more about the picture and don't want to have to open Bing in order to read it.

**Comment by neffo** [comment]
One thing with popups is that they would appear at midnight (if you are using your default local region), or at start up.

One thing that isn't made clear in the extension (and I'm going to try fix this) is if you click on the photo description it will take you to the Bing link for the image with the full text.

![image](https://user-images.githubusercontent.com/5569112/78465546-5a98e700-773a-11ea-93f1-cdadad8b8846.png)

**Comment by shbach** [comment]
Wow I can't believe I didn't realize clicking the photo description text would open up the page directly. That helps a lot actually haha

**Comment by job1925** [comment]
I would also like this feature. I would disable the indicator (because I don't like to clutter my top panel) but I sometimes (well, pretty much every time) want to check where is the picture from. So for me, it would be enough to have a notification saying:

**Wallpaper changed**
[The short description of the picture]

I don't understand why the notifications have to appear at startup or at midnight. Does it depend on the region? For me, the wallpaper changes at maybe around 10 a.m. so I would expect the notification to pop up at that time too. Or did I misunderstand something?

**Comment by neffo** [comment]
The timing is set by the response we get from Bing API. It's actually recently changed. I now get them at 5pm (midnight PST). It seems likely they are now refreshing at midnight on PST/PDT time.

I'll look at bringing back the popups though.

**Comment by job1925** [comment]
Thanks for the reply. And thanks for looking into it.
