### ISSUE TITLE
What does "Set wallpaper" mean?

### ISSUE THREAD

**Issue by Etamuk** [neffo/bing-wallpaper-gnome-extension#53]
Hello,

I have a short question. While I was translating into german I couldn't get the meaning of "Set wallpaper" in context menu from indicator. 
Does it mean, you can set the actual wallpaper as desktop background image (when this option is disabled in settings)?
Can you explain it to me please? Thank you.

**Comment by neffo** [comment]
It just forces the extension to set the desktop wallpaper (or desktop background) to the Bing picture. Useful if someone has manually set the wallpaper to something else. Wallpaper is an old-fashioned term for it, I guess.

**Comment by Etamuk** [comment]
Thank you for clarifying this. 
Maybe there could be programmed an option to describe this point, for example with a tooltip when hovering the entry in context menu. Or better:  the menu entry could be grayed out when not active (when the actual picture is already set). 

Wallpaper: Yes, I think so too. In my translation the word Wallpaper does not appear. 

By the way: I did some little improvements on german translation and will upload this soon.
Best regards.

**Comment by neffo** [comment]
Thanks Etamuk, I very much appreciate your efforts :)

Apologies for not updating this extension for a few months, I was distracted with work and other things. The version that is live on extensions.gnome.org should be working with the latest versions of GNOME (was updated yesterday).
