### ISSUE TITLE
Add option to blur the wallpaper

### ISSUE THREAD

**Issue by kshenoy** [neffo/bing-wallpaper-gnome-extension#60]
Hi, is it possible to add an option to blur the wallpaper, preferable separate sliders for blur intensity for the lock screen and the desktop background?

**Comment by shbach** [comment]
Not sure if helpful but GNOME 3.36 [blurs the lock screen now](https://blogs.gnome.org/shell-dev/2020/02/18/login-and-unlock-in-gnome-shell-3-36/).

**Comment by neffo** [comment]
Yeah and wallpapers and lockscreen wallpapers are now unified, I believe. I've not had a great chance to play with 3.36 as yet, although the extension does work fine with it (at least with Ubuntu 20.04 beta).

**Comment by neffo** [comment]
Implemented in 3e67bc2
