### ISSUE TITLE
Request for an alternative icon feature

### ISSUE THREAD

**Issue by colopatiron** [neffo/bing-wallpaper-gnome-extension#61]
Can we have an option to switch the indicator icon to something else apart from the Microsoft Bing icon? I would like to keep the indicator on, but hate seeing the Microsoft logo on my desktop,

**Comment by neffo** [comment]
This looks very possible, I've got a few ideas on how we could do that. Thanks for your suggestion.

**Comment by neffo** [comment]
Hi @colopatiron latest release has a small selection of alternative icons to choose from. Happy to new icons if you are creative!
