### ISSUE TITLE
Old images are kept longer than specified in the settings

### ISSUE THREAD

**Issue by igsol** [neffo/bing-wallpaper-gnome-extension#62]
The following settings are used:
![image](https://user-images.githubusercontent.com/14091049/70424546-3c66f700-1a78-11ea-92e2-62e2bc484012.png)

Here is a current set of directory with images:
![image](https://user-images.githubusercontent.com/14091049/70424508-2eb17180-1a78-11ea-971d-04bc0771d04e.png)

It's easy to see that number of retained images is much higher than 7 (number from settings).

**Comment by neffo** [comment]
Hi @igsol, did you enable that setting after having it disabled? Do you have images from the last 7 days in that list?

There are 77 days between 2019-09-23 and 2019-12-09, but only 37 images in that folder. We only keep track of the last 7 days of images, so if you enable that after having run the extension and keeping images for a while those images will remain in the folder.

**Comment by igsol** [comment]
> did you enable that setting after having it disabled?

IIRC the setting was enabled and 7 days were set immediately after I installed your extension.

> if you enable that after having run the extension and keeping images

It seems when I created this ticket I disabled-and-enabled the settings and right after got your reply here I rechecked the stored files.
And now I see that files older December are kept and only 8 last files in February are kept as well.
Thus all works fine starting from December.

Thank you for your help.

**Comment by neffo** [comment]
Thanks for following this up, glad it's resolved in this sense. We could keep track of all the files we've downloaded, and then enabling the setting would purge the older files...

I'll see what is feasible. Thanks for using the extension and helping to improve it.
