### ISSUE TITLE
Set background image from tray menu should force changing the background

### ISSUE THREAD

**Issue by Etamuk** [neffo/bing-wallpaper-gnome-extension#63]
Hello :-) 

Bing Wallpapers offen provides beautiful wallpapers. But sometimes I like a wallpaper so I would like to keep it some days. So I disabled the two values for changing background and lockscreen images in settings. 
Every day I am opening the bing wallpaper menu in tray to see the description of the new image. Mostly I click on it to see the wallpaper in the browser. 
If I like the bing wallpaper I go to settings and enable "Set as wallpaper" or/and "Set as lockscreen". After the new image is ready I disable it again. 

So I would like to share my suggestions you can see in the picture. 
With this menu you can see a preview of the "bing picture of the day" and you can set the picture as wallpaper on desktop, as lockscreen picture or both. 

The values in settings can be activated and are useful for users who want to change the wallpaper every day automatically. 

What do you think?
I am no programmer so I cannot realize this.

![Bildschirmfoto von 2019-12-09 12-53-55](https://user-images.githubusercontent.com/20098065/70436088-c919b100-1a88-11ea-9779-15480783c1f3.png)

**Comment by neffo** [comment]
Interesting use case!

This should be possible to implement, I'll need to look into it further though.

**Comment by neffo** [comment]
Hi @Etamuk I've put together an implementation of this, but needs a bit of work still (bit buggy atm). Let me know what you think, and again thanks for the suggestion.

**Comment by Etamuk** [comment]
Glad you didn't forgotten ist :-) 
Yes, very nice. I took a look at your screenshot (https://github.com/neffo/bing-wallpaper-gnome-extension/blob/master/screenshot/bing-screenshot.png). 

But: Did you really mean "screensaver wallpaper"? Or maybe "lockscreen wallpaper"?

**Comment by Etamuk** [comment]
Now I installed the new version with the possibility to take a look on the preview. I have to say: really really nice. Thank you for implementing it! :+1: 
BTW: new german translation is on the way
