### ISSUE TITLE
refresh button is useless?

### ISSUE THREAD

**Issue by cathaysia** [neffo/bing-wallpaper-gnome-extension#64]
Hi
I'm a China user. This extension could get ugly wallpaper some times and I try to get a new wallpaper by refresh button, but it doesn't seem to work.

If I want get a new wallpaper, the only way is change my zone(zh_CN or en_WW). One zone mean a wallpaper.

How can I get a new wallpaper in one day?

My computer is ArchLinux with Gnome. But Fedora and opensuse has same problem.

**Comment by neffo** [comment]
Hi cathaysia, the wallpaper only changes once per day per region. This is just the way Bing does it. Bing in China only supports two regions, zh_CN and en_WW, as far as I know. If you select anything else Bing sends you en_WW I believe? This isn't something the extension can change, I'm sorry.

**Comment by cathaysia** [comment]
OK, thanks for your help
