### ISSUE TITLE
Gnome crashing on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by daveginberry** [neffo/bing-wallpaper-gnome-extension#70]
Installing bing wallpaper extension on 20.04 causes  crash although system still usable and wallpaper does change
Ubuntu bug reported https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1876681
Uninstall the extension and there are then no problems.
Nice to have it fixed.

**Comment by neffo** [comment]
Hi Dave, thanks for going to the effort to report this bug, much appreciated.

Bugs that crash GNOME can be a real pain, but will take a look.

**Comment by neffo** [comment]
Hi Dave, are you able to walk me through this. Looking at the output I can't see what in particular is causing the bug. The extension should only really be active 1 minute after startup, and around midnight in your region.
If you are comfortable with command line stuff, you can help debug the extension with these commands:

```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas set org.gnome.shell.extensions.bingwallpaper debug-logging true
```

Then after a reboot or shell restart, you can create a text dump all the debug messages with this command:
```
journalctl -g BingWallpaper > bingdebuglog.txt
```

You can attach that debug log here or email it to me at ineffable@gmail.com and I'll take a look.

**Comment by daveginberry** [comment]
[bingdebuglog.txt](https://github.com/neffo/bing-wallpaper-gnome-extension/files/4602825/bingdebuglog.txt)
As requested.  As expected another Ubuntu bug report was generated but did not send.
Extension once more uninstalled.  Please advise in due course whether debug logging can be turned off and how to do this.  VMT

**Comment by neffo** [comment]
Thanks, much appreciated.

Debug logging is only for the extension itself, so if you've uninstalled it you don't need to worry about it. If you reinstall, it'll still have debug mode on, but you can disable it with this command:

```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas set org.gnome.shell.extensions.bingwallpaper debug-logging false
```

**Comment by b-lechalupe** [comment]
Greeting :smile: 

I'm also experimenting this issue today: gnome-shell crash after one minute if I'm logging in before 9AM (Switzerland time).
Can we hope for a fix?

**Comment by neffo** [comment]
This is an old bug, but probably linked to an issue with Wayland and some of the things the extension was doing that was not entirely "officially sanctioned". #82 could be related, this has some what been mitigated when Wayland is detected on newer versions of the extension.
