### ISSUE TITLE
Gnome 3.36+ blurred lockscreen background

### ISSUE THREAD

**Issue by drzraf** [neffo/bing-wallpaper-gnome-extension#73]
I tried https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/ to actually unblur the lockscreen but this overrides the Bing-background.

How to get bing-background on the lockscreen ... not blurred?

**Comment by neffo** [comment]
Related issue to #60, would be nice to have a selectable blur factor, or restrict blur to just a region of the screen. We could probably roll this into the extension as an experimental feature.

**Comment by neffo** [comment]
I've created a test branch which some initial capability if you would like to test this: https://github.com/neffo/bing-wallpaper-gnome-extension/tree/adjustable-blur

It's a bit rough, but seems to be working.

**Comment by pacho2** [comment]
Hi!

Thanks

In my case I have applied this
https://github.com/neffo/bing-wallpaper-gnome-extension/compare/adjustable-blur.patch

To v27, but enabling/disabling the functionality fails with this error

ago 24 12:23:39 dell-2017 gnome-shell[2763]: JS ERROR: TypeError: this._set_lockscreen_blur is not a function
                                             _init/<@/usr/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:159:18
ago 24 12:23:41 dell-2017 gnome-shell[2763]: JS ERROR: TypeError: this._set_lockscreen_blur is not a function
                                             _init/<@/usr/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js:159:18

**Comment by neffo** [comment]
Yeah, I'm not seeing that error myself. Are you able to download from git adjustable-blur branch?

**Comment by pacho2** [comment]
It works perfect, thanks :D

**Comment by drzraf** [comment]
Does not work for me on 20.04.
![Screenshot from 2020-10-24 22-44-11](https://user-images.githubusercontent.com/1169926/97096969-75856700-164a-11eb-9052-38076c0fbc6f.png)





- Lock screen option seems forced "on" but does not actually work.
- The "Set lockscreen image" menu item does not appear either.
- `/org/gnome/shell/extensions/bingwallpaper/debug-logging` is true (and logging works), but no specific errors is visible
- `dconf dump /org/gnome/desktop/screensaver/`:
```
[/]
color-shading-type='solid'
lock-delay=uint32 0
picture-options='zoom'
picture-uri='file:///home/foo/Pictures/20201024-BCPumpkins_FR-FR4504118344_1920x1080.jpg'
primary-color='#000000'
secondary-color='#000000'
```

**Comment by neffo** [comment]
Yeah, it still needs work atm, which is why it's still in a branch. Sorry for not making that clearer. The lockscreen option is gone for later versions of the GNOME shell as lockscreen and desktop images are unified, so you can't set them separately. You have to set the desktop wallpaper for the lockscreen to show the image.

This setting is not used:
`org.gnome.desktop.screensaver.picture-uri`

**Comment by drzraf** [comment]
> The lockscreen option is disabled for later versions of the GNOME shell as lockscreen and desktop images are unified, so you can't set them separately.

Then this is the real bug I wasn't aware of. Thank you for letting me know (I want dynamic images for my lockscreen only)

After reading a couple of reports I found:
- https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground
- https://github.com/thiggy01/ubuntu-20.04-change-gdm-background

I didn't tested yet and don't know whether they work or are compatible with bing-wallpaper and couldn't even find  an upstream bug or feature request about this.

**Comment by neffo** [comment]
It's actually by design, not so much a bug.

Looking at that first repository it looks like we could restore the original functionality (I'll consider it a feature request).

The second repo is the GDM login screen itself, which is a bit trickier and needs super user access levels. Not something I'd really want a GNOME extension having control over, personally.

**Comment by neffo** [comment]
Implemented in 3e67bc2

**Comment by danielsanfr** [comment]
First of all, thank you very much @neffo for developing this extension.

I don't know if this is the best place to ask this question, but this issue is the closest I have found about my problem.

I am using Manjaro Linux and the items on the "lock screen" tab are all disabled. I would like to know how to enable them?

![image](https://user-images.githubusercontent.com/3621711/115135916-7b08ac00-9ff2-11eb-8c44-160f0b6426ce.png)

**Thank you very much in advance for your response.**

_For now, as I am not able to use just its extension, I am also using the extension that @drzraf put in the first comment (https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/)._

**Comment by neffo** [comment]
Are you running GNOME 40? The UI being disabled generally means I'm not 100% sure it's going to work reliably (or the shell version doesn't support it). That should be communicated a bit better.

**Comment by danielsanfr** [comment]
Thank you for responding so quickly.

I don't know if this will help, but here is an image of the "about" my computer:

![Screenshot from 2021-04-18 15-46-45](https://user-images.githubusercontent.com/3621711/115157009-70373100-a05d-11eb-9070-d3b0f23a5a8e.png)

Let me know if I can execute a command to be able to show you more useful information.

**Comment by preIdiot** [comment]
I am also facing this issue on Ubuntu 20.04.02 with GNOME v3.36.8 
any update on it @neffo?


![Screenshot from 2021-04-28 13-08-16](https://user-images.githubusercontent.com/61873006/116365534-f8b68e00-a822-11eb-9064-7d06f79e9aa7.png)
![Screenshot from 2021-04-28 13-08-02](https://user-images.githubusercontent.com/61873006/116365544-fa805180-a822-11eb-9d78-bcbba41f1503.png)

**Comment by drzraf** [comment]
On Gnome 3.36.8 using the latest release of the extension, I still experience the following:
- Lock screen option seems forced "on" **but does not actually work**.
- The _"Set lockscreen image"_ menu item does not appear either.
Is the blur-feature restricted to Gnome 3.40?
Shouldn't the lockscreen feature works on Gnome 3.36 anyway?

**Comment by neffo** [comment]
Are you definitely running GDM as your lock screen? (Not LightDM)

What Distro?

**Comment by drzraf** [comment]
GDM 3.36.3 on Ubuntu 20.04. But what you just wrote **is probably** the problem: **I don't want to change the desktop wallpaper**  but only the lockscreen one.
(Because on the desktop, I may have icons, or some personal work preferences regarding wallpaper colors and geometry, what is not the case of the lock screen which gives me opportunity to see beautiful daily images)

**Comment by neffo** [comment]
Thanks for confirming, and I appreciate your use case here. There is the remote possibility of splitting the two wallpapers out with a hotpatch similar to what we are already doing with the Lockscreen Blur control, but I don't see an easy way to do that. The fact I've not seen someone manage it, and generally GNOME hackers are pretty motivated to change anything and everything, suggests the way the lockscreen works currently might not be patchable.

**Comment by drzraf** [comment]
https://askubuntu.com/questions/1135694/ubuntu-19-04-cant-change-lockscreen-background
https://github.com/PRATAP-KUMAR/focalgdm3/blob/master/focalgdm3

Patching a system-wide CSS is clearly suboptimal, but if just a simple `sudo sed -i ` could allow for subsequent extension-based background changes, it'd be nice. The above shell-script creates an alternative (properly, using `update-alternatives`)
