### ISSUE TITLE
Add the option to run a script or a command after the update.

### ISSUE THREAD

**Issue by ddddavidee** [neffo/bing-wallpaper-gnome-extension#78]
It would be nice to run a command (I Would like to run https://github.com/dylanaraps/pywal) after the wallpaper update.

**Comment by neffo** [comment]
Yeah, that could be possible. In the meantime here is something I just hacked together you could try:
https://github.com/neffo/walwatcher

**Comment by neffo** [comment]
Yeah. It's very hacky as I've not tried to do anything like that before with Python. I don't even have pywal installed, so couldn't test it.

**Comment by ddddavidee** [comment]
Ok. Thanks!
(It works very well)
