### ISSUE TITLE
Indicator show image too wide

### ISSUE THREAD

**Issue by alexislefebvre** [neffo/bing-wallpaper-gnome-extension#79]
The ratio of the image in the indicator is not correct today:

> ![image](https://user-images.githubusercontent.com/2071331/95023150-a55cd280-067b-11eb-8d5a-c3551c1041c9.png)

Is it due to the “© NASA …” text?

Or image of today may have a wrong ratio in its metadata? URL for reference: https://www.bing.com/th?id=OHR.MontageJupiterIo_FR-FR5997493588_UHD.jpg

**Comment by k1pp13** [comment]
The word-wrap fix from a few months ago needs to be added to other segments of the extension. It happened because of the info text a while back and was fixed then.

**Comment by neffo** [comment]
Yeah, we're not word wrapping or clipping text by default. I did notice this one myself, I've got a few larger changes coming through so will roll this fix in.

**Comment by alexislefebvre** [comment]
@neffo it looks like the problem is fixed, thanks. feel free to close this issue.

**Comment by neffo** [comment]
Thanks, I will close this when the fixes are live on GNOME extensions site.

**Comment by alexislefebvre** [comment]
It should be online now.
