### ISSUE TITLE
Extension doesn't set lockscreen wallpaper when using LightDM

### ISSUE THREAD

**Issue by neffo** [neffo/bing-wallpaper-gnome-extension#8]
Currently the lockscreen wallpaper is only set for GDM, and LightDM appears to use a very different configuration method (plus there are two different greeters, GTK and Unity).

Not sure how to fix this without requiring user intervention. LightDM appears likely to be discontinued in Ubuntu, so this may be a legacy problem.

If anyone has an ideas, please let me know.

**Comment by 4thguy** [comment]
I tried this once when I was still using LightDM as a greeter, specifically the Unity version.

This command should do the trick `gsettings set com.canonical.unity-greeter background '/foo/wallpaper.png'`

Source: https://askubuntu.com/a/64002

**Comment by neffo** [comment]
Cheers, that's simple enough to implement, and it looks like Ubuntu sets 'user-backgrounds' by default.

**Comment by neffo** [comment]
Hmm, this doesn't seem to solve the issue on a default install of Ubuntu with LightDM.
