### ISSUE TITLE
use symbolic svg for indicator icon

### ISSUE THREAD

**Issue by tuberry** [neffo/bing-wallpaper-gnome-extension#81]
Symbolic icons (`*-symbolic.svg`) respect font color/size, so they look more consistent with system status icons than standard ones.
![image](https://user-images.githubusercontent.com/17917040/97069132-96c16580-1600-11eb-86e5-e6b28d4043a5.png)

**Comment by neffo** [comment]
Yeah, I've got a fix for this in a testing branch (#77 ). It's been a bit held up due to work constraints and making sure it works with the new GNOME shell versions.

Thanks for the suggestion though, I do appreciate it.
