### ISSUE TITLE
"next image" option

### ISSUE THREAD

**Issue by preIdiotWeb** [neffo/bing-wallpaper-gnome-extension#83]
A next image option which pick a new image from the downloaded images.

**Comment by neffo** [comment]
Do you mean pick the existing downloaded images?

**Comment by preIdiotWeb** [comment]
yes, more precisely that folder so that the user can add additional wallpapers there. Plus a slideshow feature which will randomly change those wallpapers and in addition to it a setting section where user can set time for wallpaper change (like in every 10min or 6 hrs)
all this because it becomes a little bit boring watching the same wallpaper all day especially when you spend more than half of your day on the screen

**Comment by neffo** [comment]
See #72
