### ISSUE TITLE
Network error occured: 7

### ISSUE THREAD

**Issue by agriffis** [neffo/bing-wallpaper-gnome-extension#86]
This started happening for me on Jan 14:

```
Jan 16 21:28:42 jasperodus gnome-shell[10436]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=en-US
Jan 16 21:29:07 jasperodus gnome-shell[10436]: BingWallpaper extension: Network error occured: 7
```

I can fetch that URL at the command-line, so it's reachable. This seems to be a problem that only happens trying to fetch from the extension.

I'm working on debugging it, but figured I'd post this in case somebody else has seen it and we can compare notes.

**Comment by agriffis** [comment]
Hmm, only happens when I have a proxy.pac enabled. This config has worked for me for years, so not sure yet why it's breaking.

**Comment by neffo** [comment]
Thanks for reporting and trying to debug. The extension uses libsoup, and it looks like the proxy code has changed a bit recently, but unsure exactly how it would break it.
```
Soup.Session.prototype.add_feature.call(httpSession, new Soup.ProxyResolverDefault());
```

Is it falling over at the proxy authentication stage perhaps?

**Comment by agriffis** [comment]
Well, it's not an authenticated proxy, and more importantly, it's shouldn't be used for this connection, only for specific hosts by rules in `proxy.pac`

You mentioned the proxy code has changed recently. Could you give me a pointer to what you mean?

**Comment by agriffis** [comment]
I've upgraded to Fedora 34 which is still in development, and running GNOME 40. At the moment the extension isn't loading at all, but it was for a while, and the proxy was working fine. So I'm going to close this—it's a platform issue and not something that seems to need a change in this extension.
