### ISSUE TITLE
Last update (v28) doesn't work on Gnome Shell 3.36

### ISSUE THREAD

**Issue by alexislefebvre** [neffo/bing-wallpaper-gnome-extension#88]
I updated the extension from https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/

```
$ gnome-shell --version
GNOME Shell 3.36.4
```

I had to reinstall the v27 to have a working extension.

**Comment by Xathros1** [comment]
Get a error with the new update on GNOME Shell 3.38.2

**Comment by Xathros1** [comment]
> Get a error with the new update on GNOME Shell 3.38.2

Error was gone after restart under the said version above and Wayland

**Comment by neffo** [comment]
Thanks for the sponsorship @alexislefebvre. I'm not able to replicate the error with GNOME Shell 3.36.4:

![Screenshot from 2021-01-20 00-42-48](https://user-images.githubusercontent.com/5569112/105049517-72b6d880-5ab8-11eb-814d-4e9c9e697aef.png)

This is fresh install of Ubuntu 20.04.1 LTS in a GNOME Box, installing from the [GNOME extensions page](https://extensions.gnome.org), restarting the Shell didn't help I gather?

**Comment by alexislefebvre** [comment]
You're welcome. :slightly_smiling_face: 

It works for me now. :shrug:

Sorry for the disturbance.

**Comment by neffo** [comment]
No problems at all, thanks for the support.
