### ISSUE TITLE
Feature request: go back to previous wallpaper

### ISSUE THREAD

**Issue by quietmansoath** [neffo/bing-wallpaper-gnome-extension#89]
Hello, it would be great if there was an option to go back and use a previous day's wallpaper. On the official app from Bing for Windows, you can toggle back about 5 days or so. This way if I didn't like the one for the day, I could just hit back.

Otherwise, thank you for this really great extension. It's literally the best one out there for Bing and Gnome.

**Comment by neffo** [comment]
See #72
