### ISSUE TITLE
Issues related to migration to GNOME 40

### ISSUE THREAD

**Issue by neffo** [neffo/bing-wallpaper-gnome-extension#91]
The following issues need to be resolved before a working GNOME 40 version can be published:

- Fix crashes on Wayland with "autostart-xwayland" and "autoclose-xwayland" #82 - this is a hack, will need to remove or reimplement - DONE
- Fix extension preferences, UI is created in Glade which is no longer supported (considered harmful) and many of the properties no longer exist, and this whole thing might need to be migrated to a template - DONE
- Migrate to GTK4 - https://developer.gnome.org/gtk4/4.0/gtk-migrating-3-to-4.html - DONE (mostly)
 - GtkFileChooserButton is removed - DONE
 - GtkBuilder API has changed - DONE
 - Locale section drop down is only showing a subset of the locales available - NEEDS WORK

**Comment by neffo** [comment]
Initial (mostly) functional version is available here: https://github.com/neffo/bing-wallpaper-gnome-extension/tree/gnome-40

Has been tested with Gnome 40.rc on Fedora 33 on Xorg and Wayland.

**Comment by Spinnekop** [comment]
The download link for the gnome 40 version is the same as for the 3.38.

**Comment by neffo** [comment]
Yeah that locale issue is a strange one, no apparently reason for that to not work - but I have noticed it as well. The extension version compatible with GNOME 40 isn't on the GNOME site as yet so wouldn't be available. The README file has just been rolled over from the main branch.

**Comment by spielkind** [comment]
Looks good to me some log output:
```
Apr 09 11:07:25 xpaddy gnome-shell[2048]: validate_icon()
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension: Replace icon set to : bing-symbolic
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension/Blur: _lockscreen_blur_disable() called
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension/Blur: shell version too old, no overriding
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension/Blur: lockscreen blur strength set to 2
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension/Blur: lockscreen brightness set to 50
Apr 09 11:07:25 xpaddy gnome-shell[2048]: Attempting to add actor of type 'Gjs_ui_popupMenu_PopupMenuItem' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.
Apr 09 11:07:25 xpaddy gnome-shell[2048]: Attempting to add actor of type 'Gjs_ui_popupMenu_PopupMenuItem' to a container of type 'StBoxLayout', but the actor has already a parent of type 'StBoxLayout'.
Apr 09 11:07:25 xpaddy gnome-shell[2048]: BingWallpaper extension: next check in 60 seconds @ local time [boxed instance wrapper GIName:GLib.DateTime jsobj@0x302fe6a783d0 native@0x55684ca14460]
```

Any chance to get it merged & released?

**Comment by neffo** [comment]
There are a couple of fixes that are outstanding, particularly the locale drop-down bug in the extension preferences.

**Comment by neffo** [comment]
Last fix should be good for testing if anyone is able (particularly the preferences), please use the master branch.

**Comment by neffo** [comment]
Uploaded to https://extensions.gnome.org/extension/1262/bing-wallpaper-changer/

Should be approved in a day or two. Thanks everyone for your patience.

**Comment by Spinnekop** [comment]
Awesome. Thanks.

**Comment by neffo** [comment]
Now approved, closing this issue now
