### ISSUE TITLE
settings dialog does not fit on screen

### ISSUE THREAD

**Issue by christianrauch** [neffo/bing-wallpaper-gnome-extension#93]
The settings dialog is way too big. In my setup, it does not even fit on the screen:
![Bildschirmfoto von 2021-03-30 00-23-17](https://user-images.githubusercontent.com/8573621/112911941-55bd0800-90ee-11eb-9ad4-66304a5316cf.png)

Considering that I can fit multiple windows or an entire IDE on the screen, the settings dialog is not using the space efficiently. There is a lot of empty space between the vertically stacked options and especially the bing indicator preview is larger than needed.

The individual groups of settings could be arranged as tabs, or at least the entire area could be scrollable so that the window fits the screen.

**Comment by neffo** [comment]
Thanks for the report, yeah that looks a bit ugly there. You've actually not lost any widgets off the bottom of the screen - just text, but we can improve that.

Your screen is 768 pixels high, I gather?

**Comment by neffo** [comment]
I've just pushed a small change which will reduce the vertical height of the settings somewhat, by reducing the preview icon size.

**Comment by christianrauch** [comment]
> Your screen is 768 pixels high, I gather?

Yes, my screen resolution is quite small. It's not a big issue that prevents using the settings window. But it is surprising that the settings window consumes soo much space when other, far more complex GUI applications (Qt Creator, Steam, ...), fit very well on the screen, even when not maximised.

> I've just pushed a small change which will reduce the vertical height of the settings somewhat, by reducing the preview icon size.

Thanks. That should at least make the window fit the screen. The next easy thing after this would probably be converting this single static area of toggles into a scrollable area. Then the window can be resizes by a user and all the toggles will still be available.

**Comment by neffo** [comment]
I understand, but it's actually very much inline with other GNOME examples (see below). I'm not a fan of the Qt Creator preferences UI, it's very busy and it has a lot more options. I don't see a scroll bar as necessary.

![image](https://user-images.githubusercontent.com/5569112/112981816-097dd080-919f-11eb-9679-2dc2ef305d98.png)

**Comment by christianrauch** [comment]
These are all suggestions. I don't want to criticize your UI choices too much. I really like this GNOME extension :-)

The GNOME settings window uses indeed scrollbars. You can see this easily by resizing the window vertically.

This is pretty much a requirement since many of the settings pages are dynamic (Wi-Fi, Bluetooth, Network, Notifications, ...). Having the window statically resize to fit all the known and currently visible Wi-Fi networks (and Bluetooth connections, etc.) would likely increase the window size beyond the screen size.
