### ISSUE TITLE
GNOME40 - cannot scroll locales

### ISSUE THREAD

**Issue by Spinnekop** [neffo/bing-wallpaper-gnome-extension#95]
Can only see the language options as per the screenshot - no apparent way to scroll up to where en should be...
![Screenshot from 2021-04-07 20-31-59](https://user-images.githubusercontent.com/31868152/113923734-cba52b80-97e0-11eb-9aab-bd1c3e5a7457.png)

**Comment by Spinnekop** [comment]
Sorry - scrolling on down arrow works....

**Comment by neffo** [comment]
Yeah this is a GNOME 40 and Gtk4 migration issue #91 and as you noted elsewhere, it's not showing most of the locales.

**Comment by neffo** [comment]
Ok this is a known issue with Gtk4, we'll have to replace this with a dropdown: https://gitlab.gnome.org/GNOME/gtk/-/issues/3674
